object FrmA_2304_AirPnt: TFrmA_2304_AirPnt
  Left = 488
  Top = 113
  Width = 696
  Height = 480
  Caption = 'A 2304 Air Pnt'
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 177
    Height = 305
    Color = clMedGray
    TabOrder = 0
    object Label1: TLabel
      Left = 3
      Top = 12
      Width = 38
      Height = 13
      Alignment = taCenter
      AutoSize = False
      Caption = 'ENG'
      Color = clGreen
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label2: TLabel
      Left = 59
      Top = 12
      Width = 62
      Height = 13
      Alignment = taCenter
      Caption = 'Kinematics'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label3: TLabel
      Left = 139
      Top = 12
      Width = 30
      Height = 13
      Alignment = taCenter
      AutoSize = False
      Caption = 'HF'
      Color = clGreen
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label4: TLabel
      Left = 35
      Top = 32
      Width = 25
      Height = 13
      Alignment = taCenter
      Caption = 'Brn:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label5: TLabel
      Left = 34
      Top = 56
      Width = 27
      Height = 13
      Alignment = taCenter
      Caption = 'Rng:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label6: TLabel
      Left = 36
      Top = 80
      Width = 25
      Height = 13
      Alignment = taCenter
      Caption = 'Crs:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label7: TLabel
      Left = 35
      Top = 104
      Width = 27
      Height = 13
      Alignment = taCenter
      Caption = 'Spd:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label8: TLabel
      Left = 31
      Top = 127
      Width = 31
      Height = 13
      Alignment = taCenter
      Caption = 'Hght:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label9: TLabel
      Left = 100
      Top = 132
      Width = 15
      Height = 13
      Alignment = taCenter
      Caption = 'hft'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label10: TLabel
      Left = 29
      Top = 176
      Width = 33
      Height = 13
      Alignment = taCenter
      Caption = 'T init:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label11: TLabel
      Left = 29
      Top = 200
      Width = 37
      Height = 13
      Alignment = taCenter
      Caption = 'T upd:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object VrClock1: TVrClock
      Left = 72
      Top = 170
      Width = 49
      Height = 25
      Threaded = True
      Palette.Low = clBlack
      Palette.High = clWhite
      Style = ns7x13
      Color = clMedGray
      ParentColor = False
    end
    object Bevel1: TBevel
      Left = 0
      Top = 256
      Width = 177
      Height = 2
    end
    object Edit1: TEdit
      Left = 64
      Top = 29
      Width = 33
      Height = 21
      AutoSize = False
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      Text = '000'
    end
    object Edit2: TEdit
      Left = 64
      Top = 53
      Width = 57
      Height = 21
      AutoSize = False
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      Text = '0000.0'
    end
    object Edit3: TEdit
      Left = 64
      Top = 77
      Width = 33
      Height = 21
      AutoSize = False
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      Text = '000'
    end
    object Edit4: TEdit
      Left = 64
      Top = 101
      Width = 49
      Height = 21
      AutoSize = False
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      Text = 'qqqq q'
    end
    object Edit5: TEdit
      Left = 64
      Top = 125
      Width = 33
      Height = 21
      AutoSize = False
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
      Text = '999'
    end
    object Edit6: TEdit
      Left = 72
      Top = 197
      Width = 65
      Height = 21
      AutoSize = False
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 5
      Text = '00:00 00'
    end
    object VrDemoButton1: TVrDemoButton
      Left = 9
      Top = 222
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Apply'
      Color = clMedGray
      TabOrder = 6
    end
    object VrDemoButton2: TVrDemoButton
      Left = 105
      Top = 222
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Reset'
      Color = clMedGray
      TabOrder = 7
    end
  end
  object VrDemoButton3: TVrDemoButton
    Left = 9
    Top = 270
    Width = 64
    Height = 25
    FontEnter.Charset = DEFAULT_CHARSET
    FontEnter.Color = clWhite
    FontEnter.Height = -11
    FontEnter.Name = 'Verdana'
    FontEnter.Style = [fsBold]
    FontLeave.Charset = DEFAULT_CHARSET
    FontLeave.Color = clWhite
    FontLeave.Height = -11
    FontLeave.Name = 'Verdana'
    FontLeave.Style = [fsBold]
    Caption = 'Quit'
    Color = clMedGray
    TabOrder = 1
  end
  object VrDemoButton4: TVrDemoButton
    Left = 105
    Top = 270
    Width = 64
    Height = 25
    FontEnter.Charset = DEFAULT_CHARSET
    FontEnter.Color = clWhite
    FontEnter.Height = -11
    FontEnter.Name = 'Verdana'
    FontEnter.Style = [fsBold]
    FontLeave.Charset = DEFAULT_CHARSET
    FontLeave.Color = clWhite
    FontLeave.Height = -11
    FontLeave.Name = 'Verdana'
    FontLeave.Style = [fsBold]
    Caption = 'Help'
    Color = clMedGray
    TabOrder = 2
  end
end
