object FrmAAW_WASA_man: TFrmAAW_WASA_man
  Left = 346
  Top = 219
  Width = 332
  Height = 486
  Caption = 'AAW-WASA'
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 321
    Height = 449
    Color = clMedGray
    TabOrder = 0
    object Label1: TLabel
      Left = 75
      Top = 168
      Width = 40
      Height = 13
      Alignment = taCenter
      Caption = 'Sensor'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel1: TBevel
      Left = 0
      Top = 48
      Width = 322
      Height = 2
    end
    object Label2: TLabel
      Left = 152
      Top = 168
      Width = 46
      Height = 13
      Alignment = taCenter
      Caption = 'Weapon'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label3: TLabel
      Left = 243
      Top = 168
      Width = 36
      Height = 13
      Alignment = taCenter
      Caption = 'Status'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label4: TLabel
      Left = 11
      Top = 168
      Width = 32
      Height = 13
      Alignment = taCenter
      Caption = 'Track'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label8: TLabel
      Left = 19
      Top = 16
      Width = 76
      Height = 13
      Alignment = taCenter
      Caption = 'WASA mode:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label5: TLabel
      Left = 21
      Top = 280
      Width = 32
      Height = 13
      Alignment = taCenter
      Caption = 'TTIZ:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label6: TLabel
      Left = 19
      Top = 304
      Width = 34
      Height = 13
      Alignment = taCenter
      Caption = 'TTEZ:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label7: TLabel
      Left = 56
      Top = 280
      Width = 40
      Height = 13
      Alignment = taCenter
      Caption = '00  00'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label9: TLabel
      Left = 56
      Top = 304
      Width = 40
      Height = 13
      Alignment = taCenter
      Caption = '00  00'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label10: TLabel
      Left = 125
      Top = 280
      Width = 27
      Height = 13
      Alignment = taCenter
      Caption = 'TTA:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label11: TLabel
      Left = 160
      Top = 280
      Width = 40
      Height = 13
      Alignment = taCenter
      Caption = '00  00'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label12: TLabel
      Left = 235
      Top = 280
      Width = 31
      Height = 13
      Alignment = taCenter
      Caption = 'TTFF:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label13: TLabel
      Left = 235
      Top = 304
      Width = 31
      Height = 13
      Alignment = taCenter
      Caption = 'TTLF:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label14: TLabel
      Left = 272
      Top = 280
      Width = 40
      Height = 13
      Alignment = taCenter
      Caption = '00  00'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label15: TLabel
      Left = 272
      Top = 304
      Width = 40
      Height = 13
      Alignment = taCenter
      Caption = '00  00'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Bevel2: TBevel
      Left = 0
      Top = 408
      Width = 322
      Height = 2
    end
    object Label16: TLabel
      Left = 107
      Top = 16
      Width = 62
      Height = 13
      Alignment = taCenter
      AutoSize = False
      Caption = 'Manual'
      Color = clGreen
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label17: TLabel
      Left = 121
      Top = 304
      Width = 31
      Height = 13
      Alignment = taCenter
      Caption = 'Fdoc:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label18: TLabel
      Left = 160
      Top = 304
      Width = 8
      Height = 13
      Alignment = taCenter
      Caption = '1'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label19: TLabel
      Left = 243
      Top = 368
      Width = 62
      Height = 13
      Alignment = taCenter
      AutoSize = False
      Caption = 'Kill'
      Color = clGreen
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label20: TLabel
      Left = 243
      Top = 336
      Width = 62
      Height = 13
      Alignment = taCenter
      AutoSize = False
      Caption = 'Hol fire'
      Color = clRed
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label21: TLabel
      Left = 35
      Top = 56
      Width = 32
      Height = 13
      Alignment = taCenter
      Caption = 'Track'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label22: TLabel
      Left = 131
      Top = 56
      Width = 40
      Height = 13
      Alignment = taCenter
      Caption = 'Sensor'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label23: TLabel
      Left = 208
      Top = 56
      Width = 46
      Height = 13
      Alignment = taCenter
      Caption = 'Weapon'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel3: TBevel
      Left = -1
      Top = 160
      Width = 322
      Height = 2
    end
    object ListBox1: TListBox
      Left = 8
      Top = 186
      Width = 297
      Height = 87
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ItemHeight = 13
      Items.Strings = (
        '2  1234     SENS2          WEAPON1         NEC              '
        '1  0345     SENS1          WEAPON2         NOAUTH              ')
      ParentFont = False
      TabOrder = 0
    end
    object VrDemoButton2: TVrDemoButton
      Left = 252
      Top = 416
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Help'
      Color = clMedGray
      TabOrder = 1
    end
    object VrDemoButton3: TVrDemoButton
      Left = 7
      Top = 416
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Quit'
      Color = clMedGray
      TabOrder = 2
    end
    object VrDemoButton1: TVrDemoButton
      Left = 183
      Top = 8
      Width = 122
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Fire doctrine ...'
      Color = clMedGray
      TabOrder = 3
    end
    object VrDemoButton4: TVrDemoButton
      Left = 15
      Top = 328
      Width = 90
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Authorize'
      Color = clMedGray
      TabOrder = 4
    end
    object VrDemoButton6: TVrDemoButton
      Left = 127
      Top = 328
      Width = 90
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Inhibit eng'
      Color = clMedGray
      TabOrder = 5
    end
    object VrDemoButton5: TVrDemoButton
      Left = 15
      Top = 360
      Width = 90
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Kill'
      Color = clMedGray
      TabOrder = 6
    end
    object VrDemoButton7: TVrDemoButton
      Left = 127
      Top = 360
      Width = 90
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Miss'
      Color = clMedGray
      TabOrder = 7
    end
    object ListBox2: TListBox
      Left = 32
      Top = 74
      Width = 73
      Height = 79
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ItemHeight = 13
      Items.Strings = (
        'A 2310'
        'A 0345'
        'A2312'
        'A448              ')
      ParentFont = False
      TabOrder = 8
    end
    object ListBox3: TListBox
      Left = 128
      Top = 74
      Width = 153
      Height = 79
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ItemHeight = 13
      Items.Strings = (
        'SENS2         WEAPON1       '
        'SENS2         WEAPON2      ')
      ParentFont = False
      TabOrder = 9
    end
  end
end
