object FrmCol_avoid: TFrmCol_avoid
  Left = 243
  Top = 85
  Width = 382
  Height = 326
  Caption = 'Collision avoidance'
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 369
    Height = 289
    Color = clMedGray
    TabOrder = 0
    object Label1: TLabel
      Left = 114
      Top = 12
      Width = 35
      Height = 13
      Alignment = taCenter
      Caption = 'Mode:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label6: TLabel
      Left = 16
      Top = 43
      Width = 38
      Height = 13
      Alignment = taCenter
      Caption = 'Tracks'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel2: TBevel
      Left = 1
      Top = 239
      Width = 369
      Height = 3
    end
    object Label12: TLabel
      Left = 184
      Top = 163
      Width = 70
      Height = 13
      Alignment = taCenter
      Caption = 'Guard area:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label13: TLabel
      Left = 160
      Top = 187
      Width = 93
      Height = 13
      Alignment = taCenter
      Caption = 'Safety distance:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label21: TLabel
      Left = 184
      Top = 211
      Width = 69
      Height = 13
      Alignment = taCenter
      Caption = 'T-CPA limit:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label5: TLabel
      Left = 112
      Top = 43
      Width = 31
      Height = 13
      Alignment = taCenter
      Caption = 'TCPA'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label7: TLabel
      Left = 176
      Top = 43
      Width = 42
      Height = 13
      Alignment = taCenter
      Caption = 'Display'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label2: TLabel
      Left = 304
      Top = 163
      Width = 17
      Height = 13
      Alignment = taCenter
      Caption = 'NM'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label3: TLabel
      Left = 312
      Top = 190
      Width = 19
      Height = 13
      Alignment = taCenter
      Caption = 'yrd'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label4: TLabel
      Left = 304
      Top = 213
      Width = 21
      Height = 13
      Alignment = taCenter
      Caption = 'min'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object VrPowerButton1: TVrPowerButton
      Left = 264
      Top = 7
      Width = 89
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Caption = 'Active'
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
    end
    object GroupBox1: TGroupBox
      Left = 160
      Top = 57
      Width = 201
      Height = 94
      TabOrder = 1
      object VrPowerButton3: TVrPowerButton
        Left = 8
        Top = 10
        Width = 121
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Guard area:'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object VrPowerButton4: TVrPowerButton
        Left = 8
        Top = 37
        Width = 84
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'CDAs'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object VrPowerButton5: TVrPowerButton
        Left = 9
        Top = 64
        Width = 121
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Safe sectors'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
    end
    object VrDemoButton5: TVrDemoButton
      Left = 9
      Top = 249
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Quit'
      Color = clMedGray
      TabOrder = 2
    end
    object VrDemoButton6: TVrDemoButton
      Left = 297
      Top = 249
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Help'
      Color = clMedGray
      TabOrder = 3
    end
    object Edit6: TEdit
      Left = 10
      Top = 63
      Width = 143
      Height = 138
      AutoSize = False
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
    end
    object Edit1: TEdit
      Left = 258
      Top = 162
      Width = 39
      Height = 21
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 5
      Text = '10'
    end
    object Edit2: TEdit
      Left = 258
      Top = 186
      Width = 47
      Height = 21
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 6
      Text = '500'
    end
    object Edit3: TEdit
      Left = 258
      Top = 210
      Width = 39
      Height = 21
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 7
      Text = '5'
    end
    object ComboBox1: TComboBox
      Left = 160
      Top = 8
      Width = 97
      Height = 21
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ItemHeight = 13
      ParentFont = False
      TabOrder = 8
      Text = 'Automatic'
    end
  end
end
