object FrmEMCON_plan_editor: TFrmEMCON_plan_editor
  Left = 220
  Top = 13
  Width = 422
  Height = 480
  VertScrollBar.Position = 269
  Caption = 'EMCON plan editor'
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = -269
    Width = 393
    Height = 715
    Color = clMedGray
    TabOrder = 0
    object Label1: TLabel
      Left = 24
      Top = 9
      Width = 44
      Height = 13
      Alignment = taCenter
      Caption = 'Plan:  1'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label2: TLabel
      Left = 80
      Top = 9
      Width = 57
      Height = 13
      Alignment = taCenter
      Caption = 'Not active'
      Color = clGreen
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label3: TLabel
      Left = 24
      Top = 33
      Width = 32
      Height = 13
      Alignment = taCenter
      Caption = 'Date:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label4: TLabel
      Left = 176
      Top = 9
      Width = 43
      Height = 13
      Alignment = taCenter
      Caption = 'T-start:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label5: TLabel
      Left = 177
      Top = 33
      Width = 41
      Height = 13
      Alignment = taCenter
      Caption = 'T-stop:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Edit1: TEdit
      Left = 62
      Top = 32
      Width = 91
      Height = 21
      AutoSize = False
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      Text = 'dd mm yyyy'
    end
    object Edit2: TEdit
      Left = 222
      Top = 8
      Width = 51
      Height = 21
      AutoSize = False
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      Text = '00:00'
    end
    object Edit3: TEdit
      Left = 222
      Top = 32
      Width = 51
      Height = 21
      AutoSize = False
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      Text = '23:59'
    end
    object GroupBox1: TGroupBox
      Left = 8
      Top = 56
      Width = 377
      Height = 617
      TabOrder = 3
      object Label6: TLabel
        Left = 9
        Top = 13
        Width = 105
        Height = 13
        Alignment = taCenter
        Caption = 'Survelliance radar'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label9: TLabel
        Left = 9
        Top = 133
        Width = 67
        Height = 13
        Alignment = taCenter
        Caption = 'Track radar'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label11: TLabel
        Left = 9
        Top = 221
        Width = 25
        Height = 13
        Alignment = taCenter
        Caption = 'ECM'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label13: TLabel
        Left = 9
        Top = 309
        Width = 89
        Height = 13
        Alignment = taCenter
        Caption = 'Communication'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label14: TLabel
        Left = 9
        Top = 429
        Width = 21
        Height = 13
        Alignment = taCenter
        Caption = 'E/O'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label16: TLabel
        Left = 9
        Top = 517
        Width = 47
        Height = 13
        Alignment = taCenter
        Caption = 'Acoustic'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object GroupBox2: TGroupBox
        Left = 8
        Top = 26
        Width = 361
        Height = 101
        TabOrder = 0
        object Label7: TLabel
          Left = 299
          Top = 17
          Width = 57
          Height = 13
          Alignment = taCenter
          Caption = 'Not active'
          Color = clGreen
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object VrPowerButton1: TVrPowerButton
          Left = 6
          Top = 12
          Width = 102
          Height = 25
          Palette.Low = clGray
          Palette.High = clLime
          Caption = 'Surv radar 1'
          Color = clMedGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
        end
        object VrPowerButton2: TVrPowerButton
          Left = 5
          Top = 41
          Width = 102
          Height = 25
          Palette.Low = clGray
          Palette.High = clLime
          Caption = 'Surv radar 2'
          Color = clMedGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 1
        end
        object VrPowerButton3: TVrPowerButton
          Left = 5
          Top = 70
          Width = 102
          Height = 25
          Palette.Low = clGray
          Palette.High = clLime
          Caption = 'Surv radar 3'
          Color = clMedGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 2
        end
        object Edit4: TEdit
          Left = 110
          Top = 12
          Width = 186
          Height = 25
          AutoSize = False
          Color = clGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 3
        end
        object Edit5: TEdit
          Left = 110
          Top = 42
          Width = 186
          Height = 25
          AutoSize = False
          Color = clGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 4
        end
        object Edit6: TEdit
          Left = 110
          Top = 71
          Width = 186
          Height = 25
          AutoSize = False
          Color = clGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 5
        end
      end
      object GroupBox3: TGroupBox
        Left = 8
        Top = 146
        Width = 361
        Height = 71
        TabOrder = 1
        object Label8: TLabel
          Left = 299
          Top = 17
          Width = 57
          Height = 13
          Alignment = taCenter
          Caption = 'Not active'
          Color = clGreen
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label10: TLabel
          Left = 300
          Top = 49
          Width = 57
          Height = 13
          Alignment = taCenter
          Caption = 'Not active'
          Color = clGreen
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object VrPowerButton4: TVrPowerButton
          Left = 6
          Top = 12
          Width = 102
          Height = 25
          Palette.Low = clGray
          Palette.High = clLime
          Caption = 'Track radar 1'
          Color = clMedGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
        end
        object VrPowerButton5: TVrPowerButton
          Left = 5
          Top = 41
          Width = 102
          Height = 25
          Palette.Low = clGray
          Palette.High = clLime
          Caption = 'Track radar n'
          Color = clMedGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 1
        end
        object Edit7: TEdit
          Left = 110
          Top = 12
          Width = 186
          Height = 25
          AutoSize = False
          Color = clGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 2
        end
        object Edit8: TEdit
          Left = 110
          Top = 42
          Width = 186
          Height = 25
          AutoSize = False
          Color = clGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 3
        end
      end
      object GroupBox4: TGroupBox
        Left = 8
        Top = 234
        Width = 361
        Height = 71
        TabOrder = 2
        object Label12: TLabel
          Left = 299
          Top = 49
          Width = 57
          Height = 13
          Alignment = taCenter
          Caption = 'Not active'
          Color = clGreen
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object VrPowerButton6: TVrPowerButton
          Left = 6
          Top = 12
          Width = 102
          Height = 25
          Palette.Low = clGray
          Palette.High = clLime
          Caption = 'ECM 1'
          Color = clMedGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
        end
        object VrPowerButton7: TVrPowerButton
          Left = 5
          Top = 41
          Width = 102
          Height = 25
          Palette.Low = clGray
          Palette.High = clLime
          Caption = 'ECM 2'
          Color = clMedGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 1
        end
        object Edit9: TEdit
          Left = 110
          Top = 12
          Width = 186
          Height = 25
          AutoSize = False
          Color = clGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 2
        end
        object Edit10: TEdit
          Left = 110
          Top = 42
          Width = 186
          Height = 25
          AutoSize = False
          Color = clGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 3
        end
      end
      object GroupBox5: TGroupBox
        Left = 8
        Top = 322
        Width = 361
        Height = 101
        TabOrder = 3
        object VrPowerButton8: TVrPowerButton
          Left = 6
          Top = 12
          Width = 102
          Height = 25
          Palette.Low = clGray
          Palette.High = clLime
          Caption = 'Comm.1'
          Color = clMedGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
        end
        object VrPowerButton9: TVrPowerButton
          Left = 5
          Top = 41
          Width = 102
          Height = 25
          Palette.Low = clGray
          Palette.High = clLime
          Caption = 'Comm. 2'
          Color = clMedGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 1
        end
        object VrPowerButton10: TVrPowerButton
          Left = 5
          Top = 70
          Width = 102
          Height = 25
          Palette.Low = clGray
          Palette.High = clLime
          Caption = 'Comm. 3'
          Color = clMedGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 2
        end
        object Edit11: TEdit
          Left = 110
          Top = 12
          Width = 186
          Height = 25
          AutoSize = False
          Color = clGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 3
        end
        object Edit12: TEdit
          Left = 110
          Top = 42
          Width = 186
          Height = 25
          AutoSize = False
          Color = clGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 4
        end
        object Edit13: TEdit
          Left = 110
          Top = 71
          Width = 186
          Height = 25
          AutoSize = False
          Color = clGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 5
        end
      end
      object GroupBox6: TGroupBox
        Left = 8
        Top = 442
        Width = 361
        Height = 71
        TabOrder = 4
        object Label15: TLabel
          Left = 299
          Top = 17
          Width = 57
          Height = 13
          Alignment = taCenter
          Caption = 'Not active'
          Color = clGreen
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object VrPowerButton11: TVrPowerButton
          Left = 6
          Top = 12
          Width = 102
          Height = 25
          Palette.Low = clGray
          Palette.High = clLime
          Caption = 'E/O 1'
          Color = clMedGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
        end
        object VrPowerButton12: TVrPowerButton
          Left = 5
          Top = 41
          Width = 102
          Height = 25
          Palette.Low = clGray
          Palette.High = clLime
          Caption = 'E/O n'
          Color = clMedGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 1
        end
        object Edit14: TEdit
          Left = 110
          Top = 12
          Width = 186
          Height = 25
          AutoSize = False
          Color = clGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 2
        end
        object Edit15: TEdit
          Left = 110
          Top = 42
          Width = 186
          Height = 25
          AutoSize = False
          Color = clGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 3
        end
      end
      object GroupBox7: TGroupBox
        Left = 8
        Top = 530
        Width = 361
        Height = 71
        TabOrder = 5
        object Label17: TLabel
          Left = 299
          Top = 17
          Width = 57
          Height = 13
          Alignment = taCenter
          Caption = 'Not active'
          Color = clGreen
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object VrPowerButton13: TVrPowerButton
          Left = 6
          Top = 12
          Width = 102
          Height = 25
          Palette.Low = clGray
          Palette.High = clLime
          Caption = 'Sonar 1'
          Color = clMedGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
        end
        object VrPowerButton14: TVrPowerButton
          Left = 5
          Top = 41
          Width = 102
          Height = 25
          Palette.Low = clGray
          Palette.High = clLime
          Caption = 'Sonar 2'
          Color = clMedGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 1
        end
        object Edit16: TEdit
          Left = 110
          Top = 12
          Width = 186
          Height = 25
          AutoSize = False
          Color = clGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 2
        end
        object Edit17: TEdit
          Left = 110
          Top = 42
          Width = 186
          Height = 25
          AutoSize = False
          Color = clGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 3
        end
      end
    end
    object VrDemoButton1: TVrDemoButton
      Left = 17
      Top = 680
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'OK'
      Color = clMedGray
      TabOrder = 4
    end
    object VrDemoButton2: TVrDemoButton
      Left = 89
      Top = 680
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Apply'
      Color = clMedGray
      TabOrder = 5
    end
    object VrDemoButton3: TVrDemoButton
      Left = 161
      Top = 680
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Reset'
      Color = clMedGray
      TabOrder = 6
    end
    object VrDemoButton4: TVrDemoButton
      Left = 233
      Top = 680
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Cancel'
      Color = clMedGray
      TabOrder = 7
    end
    object VrDemoButton5: TVrDemoButton
      Left = 313
      Top = 680
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Help'
      Color = clMedGray
      TabOrder = 8
    end
  end
end
