object FrmEXOCET_engagement: TFrmEXOCET_engagement
  Left = 83
  Top = 38
  Width = 408
  Height = 482
  Caption = 'EXOCET engagement'
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  Menu = MainMenu1
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 377
    Height = 693
    Color = clMedGray
    TabOrder = 0
    object Label1: TLabel
      Left = 16
      Top = 12
      Width = 45
      Height = 13
      Alignment = taCenter
      Caption = 'General'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label5: TLabel
      Left = 192
      Top = 12
      Width = 83
      Height = 13
      Alignment = taCenter
      Caption = 'EP information'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label14: TLabel
      Left = 16
      Top = 116
      Width = 101
      Height = 13
      Alignment = taCenter
      Caption = 'Salvo information'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label20: TLabel
      Left = 16
      Top = 212
      Width = 105
      Height = 13
      Alignment = taCenter
      Caption = 'Fire authorizations'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label27: TLabel
      Left = 16
      Top = 316
      Width = 66
      Height = 13
      Alignment = taCenter
      Caption = 'Target data'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label35: TLabel
      Left = 16
      Top = 484
      Width = 106
      Height = 13
      Alignment = taCenter
      Caption = 'Missile information'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object GroupBox1: TGroupBox
      Left = 16
      Top = 25
      Width = 169
      Height = 80
      TabOrder = 0
      object Label2: TLabel
        Left = 25
        Top = 15
        Width = 42
        Height = 13
        Alignment = taCenter
        Caption = 'Config:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label3: TLabel
        Left = 21
        Top = 35
        Width = 47
        Height = 13
        Alignment = taCenter
        Caption = 'Activity:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label4: TLabel
        Left = 16
        Top = 55
        Width = 52
        Height = 13
        Alignment = taCenter
        Caption = 'Urgency:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label6: TLabel
        Left = 73
        Top = 15
        Width = 88
        Height = 13
        Alignment = taCenter
        AutoSize = False
        Caption = 'Centralized'
        Color = clGreen
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
      end
      object Label7: TLabel
        Left = 73
        Top = 34
        Width = 88
        Height = 13
        Alignment = taCenter
        AutoSize = False
        Caption = 'Firing'
        Color = clGreen
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
      end
      object Label8: TLabel
        Left = 73
        Top = 55
        Width = 88
        Height = 13
        Alignment = taCenter
        AutoSize = False
        Caption = 'Normal'
        Color = clGreen
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
      end
    end
    object GroupBox2: TGroupBox
      Left = 192
      Top = 24
      Width = 177
      Height = 81
      TabOrder = 1
      object Label9: TLabel
        Left = 9
        Top = 15
        Width = 57
        Height = 13
        Alignment = taCenter
        Caption = 'EP status:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label10: TLabel
        Left = 5
        Top = 35
        Width = 62
        Height = 13
        Alignment = taCenter
        Caption = 'Cancel EP:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label11: TLabel
        Left = 72
        Top = 35
        Width = 88
        Height = 13
        Alignment = taCenter
        AutoSize = False
        Caption = 'Authorized'
        Color = clGreen
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
      end
      object Label12: TLabel
        Left = 73
        Top = 16
        Width = 88
        Height = 13
        Alignment = taCenter
        AutoSize = False
        Caption = 'Not validated'
        Color = clRed
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
      end
      object Label13: TLabel
        Left = 9
        Top = 56
        Width = 152
        Height = 13
        Alignment = taCenter
        AutoSize = False
        Caption = 'EP execution in progress'
        Color = clRed
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
      end
    end
    object GroupBox3: TGroupBox
      Left = 16
      Top = 130
      Width = 353
      Height = 71
      TabOrder = 2
      object Label15: TLabel
        Left = 12
        Top = 14
        Width = 29
        Height = 13
        Alignment = taCenter
        Caption = 'Size:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label16: TLabel
        Left = 112
        Top = 15
        Width = 33
        Height = 13
        Alignment = taCenter
        Caption = 'Type:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label17: TLabel
        Left = 153
        Top = 15
        Width = 88
        Height = 13
        Alignment = taCenter
        AutoSize = False
        Caption = 'DTOT'
        Color = clGreen
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
      end
      object Label18: TLabel
        Left = 9
        Top = 39
        Width = 88
        Height = 13
        Alignment = taCenter
        AutoSize = False
        Caption = 'TOT achieved'
        Color = clGreen
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
      end
      object Label19: TLabel
        Left = 117
        Top = 39
        Width = 28
        Height = 13
        Alignment = taCenter
        Caption = 'TOT:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Edit1: TEdit
        Left = 46
        Top = 11
        Width = 25
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        Text = '1'
      end
      object ComboBox1: TComboBox
        Left = 248
        Top = 10
        Width = 81
        Height = 21
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ItemHeight = 13
        ParentFont = False
        TabOrder = 1
        Text = '    -'
      end
      object Edit2: TEdit
        Left = 150
        Top = 35
        Width = 91
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        Text = '15:02 09'
      end
      object VrDemoButton1: TVrDemoButton
        Left = 249
        Top = 35
        Width = 80
        Height = 25
        FontEnter.Charset = DEFAULT_CHARSET
        FontEnter.Color = clWhite
        FontEnter.Height = -11
        FontEnter.Name = 'Verdana'
        FontEnter.Style = [fsBold]
        FontLeave.Charset = DEFAULT_CHARSET
        FontLeave.Color = clWhite
        FontLeave.Height = -11
        FontLeave.Name = 'Verdana'
        FontLeave.Style = [fsBold]
        Caption = 'Apply'
        Color = clMedGray
        TabOrder = 3
      end
    end
    object GroupBox4: TGroupBox
      Left = 16
      Top = 224
      Width = 353
      Height = 81
      TabOrder = 3
      object Label21: TLabel
        Left = 49
        Top = 15
        Width = 64
        Height = 13
        Alignment = taCenter
        Caption = 'Overall FA:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label22: TLabel
        Left = 13
        Top = 35
        Width = 100
        Height = 13
        Alignment = taCenter
        Caption = 'Control panel FA:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label23: TLabel
        Left = 120
        Top = 35
        Width = 88
        Height = 13
        Alignment = taCenter
        AutoSize = False
        Caption = 'Authorized'
        Color = clGreen
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
      end
      object Label24: TLabel
        Left = 121
        Top = 16
        Width = 88
        Height = 13
        Alignment = taCenter
        AutoSize = False
        Caption = 'Not validated'
        Color = clRed
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
      end
      object Label25: TLabel
        Left = 18
        Top = 55
        Width = 95
        Height = 13
        Alignment = taCenter
        Caption = 'Safety panel FA:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label26: TLabel
        Left = 121
        Top = 56
        Width = 88
        Height = 13
        Alignment = taCenter
        AutoSize = False
        Caption = 'Not authorized'
        Color = clRed
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
      end
      object VrPowerButton1: TVrPowerButton
        Left = 232
        Top = 15
        Width = 89
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Fire auth'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
    end
    object GroupBox5: TGroupBox
      Left = 16
      Top = 329
      Width = 353
      Height = 144
      TabOrder = 4
      object Label28: TLabel
        Left = 8
        Top = 12
        Width = 15
        Height = 13
        Alignment = taCenter
        Caption = 'TN'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label29: TLabel
        Left = 74
        Top = 12
        Width = 18
        Height = 13
        Alignment = taCenter
        Caption = 'Msl'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label30: TLabel
        Left = 104
        Top = 12
        Width = 23
        Height = 13
        Alignment = taCenter
        Caption = 'TSS'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label31: TLabel
        Left = 144
        Top = 12
        Width = 43
        Height = 13
        Alignment = taCenter
        Caption = 'Est.Rng'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label32: TLabel
        Left = 224
        Top = 12
        Width = 14
        Height = 13
        Alignment = taCenter
        Caption = 'FA'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label33: TLabel
        Left = 8
        Top = 108
        Width = 48
        Height = 13
        Alignment = taCenter
        Caption = 'S  1234'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object Label34: TLabel
        Left = 257
        Top = 104
        Width = 88
        Height = 33
        Alignment = taCenter
        AutoSize = False
        Caption = 'Too many '#13#10'surface tracks'
        Color = clRed
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
      end
      object ListBox1: TListBox
        Left = 8
        Top = 32
        Width = 249
        Height = 65
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ItemHeight = 13
        Items.Strings = (
          'S  1234     1      12                          Y'
          'S  1235     1        3                          Y'
          'B  1236     1        5      050.0            Y')
        ParentFont = False
        TabOrder = 0
      end
      object VrDemoButton2: TVrDemoButton
        Left = 265
        Top = 35
        Width = 64
        Height = 25
        FontEnter.Charset = DEFAULT_CHARSET
        FontEnter.Color = clWhite
        FontEnter.Height = -11
        FontEnter.Name = 'Verdana'
        FontEnter.Style = [fsBold]
        FontLeave.Charset = DEFAULT_CHARSET
        FontLeave.Color = clWhite
        FontLeave.Height = -11
        FontLeave.Name = 'Verdana'
        FontLeave.Style = [fsBold]
        Caption = 'Break'
        Color = clMedGray
        TabOrder = 1
      end
      object VrDemoButton3: TVrDemoButton
        Left = 265
        Top = 67
        Width = 64
        Height = 25
        FontEnter.Charset = DEFAULT_CHARSET
        FontEnter.Color = clWhite
        FontEnter.Height = -11
        FontEnter.Name = 'Verdana'
        FontEnter.Style = [fsBold]
        FontLeave.Charset = DEFAULT_CHARSET
        FontLeave.Color = clWhite
        FontLeave.Height = -11
        FontLeave.Name = 'Verdana'
        FontLeave.Style = [fsBold]
        Caption = 'Set'
        Color = clMedGray
        TabOrder = 2
      end
      object Edit3: TEdit
        Left = 70
        Top = 107
        Width = 19
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
        Text = '1'
      end
      object Edit4: TEdit
        Left = 94
        Top = 107
        Width = 27
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 4
        Text = '12'
      end
      object Edit5: TEdit
        Left = 126
        Top = 107
        Width = 51
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 5
        Text = '000.0'
      end
    end
    object GroupBox6: TGroupBox
      Left = 16
      Top = 497
      Width = 353
      Height = 184
      TabOrder = 5
      object Label36: TLabel
        Left = 24
        Top = 20
        Width = 100
        Height = 13
        Alignment = taCenter
        Caption = 'Missile allocation:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label37: TLabel
        Left = 24
        Top = 67
        Width = 52
        Height = 26
        Alignment = taCenter
        Caption = 'Pt'#13#10'Launcher'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label38: TLabel
        Left = 24
        Top = 136
        Width = 52
        Height = 26
        Alignment = taCenter
        Caption = 'Stb'#13#10'Launcher'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label40: TLabel
        Left = 104
        Top = 44
        Width = 36
        Height = 13
        Alignment = taCenter
        Caption = 'Status'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label41: TLabel
        Left = 184
        Top = 44
        Width = 15
        Height = 13
        Alignment = taCenter
        Caption = 'TN'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label42: TLabel
        Left = 240
        Top = 44
        Width = 18
        Height = 13
        Alignment = taCenter
        Caption = 'Tof'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label43: TLabel
        Left = 280
        Top = 44
        Width = 16
        Height = 13
        Alignment = taCenter
        Caption = 'SA'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label39: TLabel
        Left = 95
        Top = 64
        Width = 8
        Height = 13
        Alignment = taCenter
        Caption = '2'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object Label49: TLabel
        Left = 95
        Top = 85
        Width = 8
        Height = 13
        Alignment = taCenter
        Caption = '4'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object Label50: TLabel
        Left = 104
        Top = 116
        Width = 36
        Height = 13
        Alignment = taCenter
        Caption = 'Status'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label51: TLabel
        Left = 184
        Top = 116
        Width = 15
        Height = 13
        Alignment = taCenter
        Caption = 'TN'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label52: TLabel
        Left = 240
        Top = 116
        Width = 18
        Height = 13
        Alignment = taCenter
        Caption = 'Tof'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label53: TLabel
        Left = 280
        Top = 116
        Width = 16
        Height = 13
        Alignment = taCenter
        Caption = 'SA'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label59: TLabel
        Left = 95
        Top = 136
        Width = 8
        Height = 13
        Alignment = taCenter
        Caption = '1'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object Label60: TLabel
        Left = 95
        Top = 158
        Width = 8
        Height = 13
        Alignment = taCenter
        Caption = '3'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object RadioButton1: TRadioButton
        Left = 135
        Top = 20
        Width = 82
        Height = 17
        Caption = 'Automatic'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object RadioButton2: TRadioButton
        Left = 223
        Top = 20
        Width = 82
        Height = 17
        Caption = 'Manual'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object GroupBox7: TGroupBox
        Left = 104
        Top = 56
        Width = 233
        Height = 49
        TabOrder = 2
        object Label44: TLabel
          Left = 5
          Top = 10
          Width = 60
          Height = 13
          Alignment = taCenter
          AutoSize = False
          Caption = 'Usable'
          Color = clGreen
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label45: TLabel
          Left = 5
          Top = 30
          Width = 60
          Height = 13
          Alignment = taCenter
          AutoSize = False
          Caption = 'Away'
          Color = clRed
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label46: TLabel
          Left = 79
          Top = 9
          Width = 44
          Height = 13
          Alignment = taCenter
          Caption = 'S 1234'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Label47: TLabel
          Left = 79
          Top = 30
          Width = 44
          Height = 13
          Alignment = taCenter
          Caption = 'S 1235'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Label48: TLabel
          Left = 135
          Top = 9
          Width = 24
          Height = 13
          Alignment = taCenter
          Caption = '250'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Bevel1: TBevel
          Left = 200
          Top = 8
          Width = 2
          Height = 41
        end
        object VrPowerButton2: TVrPowerButton
          Left = 176
          Top = 9
          Width = 17
          Height = 17
          Palette.Low = clGray
          Palette.High = clLime
          Color = clMedGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
        end
        object VrPowerButton3: TVrPowerButton
          Left = 176
          Top = 29
          Width = 17
          Height = 17
          Palette.Low = clGray
          Palette.High = clLime
          Color = clMedGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 1
        end
      end
      object GroupBox8: TGroupBox
        Left = 104
        Top = 128
        Width = 233
        Height = 49
        TabOrder = 3
        object Label54: TLabel
          Left = 5
          Top = 31
          Width = 60
          Height = 13
          Alignment = taCenter
          AutoSize = False
          Caption = 'P_usable'
          Color = clOlive
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label57: TLabel
          Left = 79
          Top = 30
          Width = 44
          Height = 13
          Alignment = taCenter
          Caption = 'B 1236'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Label58: TLabel
          Left = 135
          Top = 29
          Width = 24
          Height = 13
          Alignment = taCenter
          Caption = '100'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Bevel2: TBevel
          Left = 200
          Top = 8
          Width = 2
          Height = 41
        end
        object Label55: TLabel
          Left = 8
          Top = 8
          Width = 28
          Height = 13
          Alignment = taCenter
          Caption = 'Avail'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
        end
        object VrPowerButton4: TVrPowerButton
          Left = 176
          Top = 9
          Width = 17
          Height = 17
          Palette.Low = clGray
          Palette.High = clLime
          Color = clMedGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
        end
        object VrPowerButton5: TVrPowerButton
          Left = 176
          Top = 29
          Width = 17
          Height = 17
          Palette.Low = clGray
          Palette.High = clLime
          Color = clMedGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
          TabOrder = 1
        end
      end
    end
  end
  object MainMenu1: TMainMenu
    Left = 440
    Top = 16
    object Settings1: TMenuItem
      Caption = 'Settings'
    end
    object Engagementplan1: TMenuItem
      Caption = 'Engagement plan'
    end
  end
end
