object FrmHal110: TFrmHal110
  Left = 623
  Top = 103
  Width = 359
  Height = 480
  VertScrollBar.Position = 182
  Caption = 'Hal 110'
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = -182
    Width = 329
    Height = 700
    Color = clMedGray
    TabOrder = 0
    object Label14: TLabel
      Left = 9
      Top = 51
      Width = 46
      Height = 13
      Alignment = taCenter
      Caption = 'Director'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label25: TLabel
      Left = 176
      Top = 83
      Width = 129
      Height = 13
      Alignment = taCenter
      AutoSize = False
      Caption = 'Radar no rad zone'
      Color = clRed
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label26: TLabel
      Left = 176
      Top = 99
      Width = 129
      Height = 13
      Alignment = taCenter
      AutoSize = False
      Caption = 'Multiple target'
      Color = clRed
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label27: TLabel
      Left = 176
      Top = 115
      Width = 129
      Height = 13
      Alignment = taCenter
      AutoSize = False
      Caption = 'Track on missile'
      Color = clRed
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label28: TLabel
      Left = 176
      Top = 131
      Width = 129
      Height = 13
      Alignment = taCenter
      AutoSize = False
      Caption = 'Possible kill'
      Color = clOlive
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label29: TLabel
      Left = 9
      Top = 158
      Width = 60
      Height = 13
      Alignment = taCenter
      Caption = 'Rng jump:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label30: TLabel
      Left = 121
      Top = 159
      Width = 19
      Height = 13
      Alignment = taCenter
      Caption = 'yrd'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel2: TBevel
      Left = 0
      Top = 184
      Width = 329
      Height = 2
    end
    object Label34: TLabel
      Left = 105
      Top = 218
      Width = 19
      Height = 26
      Alignment = taCenter
      Caption = '-25'#13#10'mil'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel3: TBevel
      Left = 0
      Top = 512
      Width = 329
      Height = 2
    end
    object Bevel4: TBevel
      Left = 8
      Top = 656
      Width = 329
      Height = 2
    end
    object Label1: TLabel
      Left = 9
      Top = 190
      Width = 65
      Height = 13
      Alignment = taCenter
      Caption = 'Misdistance'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label2: TLabel
      Left = 80
      Top = 246
      Width = 23
      Height = 26
      Alignment = taCenter
      Caption = '+25'#13#10'mil'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label3: TLabel
      Left = 80
      Top = 422
      Width = 19
      Height = 26
      Alignment = taCenter
      Caption = '-25'#13#10'mil'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label4: TLabel
      Left = 9
      Top = 486
      Width = 25
      Height = 13
      Alignment = taCenter
      Caption = 'Brn:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label5: TLabel
      Left = 41
      Top = 486
      Width = 34
      Height = 13
      Alignment = taCenter
      Caption = '-00.0'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label6: TLabel
      Left = 81
      Top = 486
      Width = 17
      Height = 13
      Alignment = taCenter
      Caption = 'mil'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label7: TLabel
      Left = 120
      Top = 486
      Width = 29
      Height = 13
      Alignment = taCenter
      Caption = 'Elev:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label8: TLabel
      Left = 152
      Top = 486
      Width = 37
      Height = 13
      Alignment = taCenter
      Caption = '+23.8'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label9: TLabel
      Left = 193
      Top = 486
      Width = 17
      Height = 13
      Alignment = taCenter
      Caption = 'mil'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label10: TLabel
      Left = 177
      Top = 214
      Width = 25
      Height = 13
      Alignment = taCenter
      Caption = 'Brn:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label31: TLabel
      Left = 41
      Top = 318
      Width = 29
      Height = 13
      Alignment = taCenter
      Caption = 'Elev:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label32: TLabel
      Left = 41
      Top = 334
      Width = 28
      Height = 13
      Alignment = taCenter
      Caption = '10.0'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label33: TLabel
      Left = 171
      Top = 230
      Width = 36
      Height = 13
      Alignment = taCenter
      Caption = '100.0'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object VrScope1: TVrScope
      Left = 104
      Top = 248
      Width = 201
      Height = 201
      Interval = 100
      Channels = <>
      GridSize = 20
      GridColor = clBlack
      BaseColor = clBlack
      Frequency = 1
      Threaded = True
      Color = clGreen
    end
    object Label35: TLabel
      Left = 280
      Top = 222
      Width = 23
      Height = 26
      Alignment = taCenter
      Caption = '+25'#13#10'mil'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Edit1: TEdit
      Left = 72
      Top = 154
      Width = 41
      Height = 21
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      Text = '200'
    end
    object VrPowerButton2: TVrPowerButton
      Left = 178
      Top = 152
      Width = 127
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Caption = 'TOJ enabled'
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
    end
    object GroupBox1: TGroupBox
      Left = 8
      Top = 6
      Width = 297
      Height = 43
      TabOrder = 2
      object Label11: TLabel
        Left = 8
        Top = 19
        Width = 89
        Height = 13
        Alignment = taCenter
        AutoSize = False
        Caption = 'Tx auth'
        Color = clGreen
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
      end
      object Label12: TLabel
        Left = 104
        Top = 19
        Width = 89
        Height = 13
        Alignment = taCenter
        AutoSize = False
        Caption = 'Radiating'
        Color = clGreen
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
      end
      object Label13: TLabel
        Left = 200
        Top = 19
        Width = 89
        Height = 13
        Alignment = taCenter
        AutoSize = False
        Caption = 'Jammed'
        Color = clRed
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
      end
    end
    object GroupBox2: TGroupBox
      Left = 8
      Top = 62
      Width = 161
      Height = 83
      TabOrder = 3
      object Label15: TLabel
        Left = 17
        Top = 19
        Width = 25
        Height = 13
        Alignment = taCenter
        Caption = 'Brn:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label16: TLabel
        Left = 14
        Top = 37
        Width = 29
        Height = 13
        Alignment = taCenter
        Caption = 'Elev:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label17: TLabel
        Left = 17
        Top = 55
        Width = 27
        Height = 13
        Alignment = taCenter
        Caption = 'Rng:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label18: TLabel
        Left = 48
        Top = 19
        Width = 36
        Height = 13
        Alignment = taCenter
        Caption = '000.0'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object Label19: TLabel
        Left = 48
        Top = 38
        Width = 42
        Height = 13
        Alignment = taCenter
        Caption = '-000.0'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object Label20: TLabel
        Left = 48
        Top = 57
        Width = 40
        Height = 13
        Alignment = taCenter
        Caption = '00000'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object Label21: TLabel
        Left = 96
        Top = 56
        Width = 19
        Height = 13
        Alignment = taCenter
        Caption = 'yrd'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label22: TLabel
        Left = 128
        Top = 19
        Width = 27
        Height = 13
        Alignment = taCenter
        Caption = 'K-bj'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object Label23: TLabel
        Left = 129
        Top = 38
        Width = 16
        Height = 13
        Alignment = taCenter
        Caption = 'TV'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object Label24: TLabel
        Left = 129
        Top = 57
        Width = 22
        Height = 13
        Alignment = taCenter
        Caption = 'K-b'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
      end
    end
    object VrPowerButton1: TVrPowerButton
      Left = 10
      Top = 520
      Width = 103
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Caption = 'TV camera'
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
    end
    object GroupBox4: TGroupBox
      Left = 8
      Top = 546
      Width = 145
      Height = 41
      TabOrder = 5
      object Label36: TLabel
        Left = 6
        Top = 15
        Width = 28
        Height = 13
        Alignment = taCenter
        Caption = 'FOV:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object ComboBox2: TComboBox
        Left = 40
        Top = 12
        Width = 97
        Height = 21
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ItemHeight = 13
        ParentFont = False
        TabOrder = 0
        Text = '     -'
      end
    end
    object VrPowerButton3: TVrPowerButton
      Left = 162
      Top = 560
      Width = 63
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Caption = 'Wiper'
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 6
    end
    object VrDemoButton1: TVrDemoButton
      Left = 241
      Top = 559
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Spray'
      Color = clMedGray
      TabOrder = 7
    end
    object GroupBox5: TGroupBox
      Left = 8
      Top = 605
      Width = 321
      Height = 41
      TabOrder = 8
      object Label38: TLabel
        Left = 6
        Top = 15
        Width = 35
        Height = 13
        Alignment = taCenter
        Caption = 'Mode:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label39: TLabel
        Left = 150
        Top = 15
        Width = 29
        Height = 13
        Alignment = taCenter
        Caption = 'Size:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object VrSpinner1: TVrSpinner
        Left = 184
        Top = 10
        Width = 97
        Height = 25
        Orientation = voHorizontal
        Palette.Low = clMaroon
        Palette.High = clWhite
        TabOrder = 2
      end
      object Edit2: TEdit
        Left = 217
        Top = 12
        Width = 26
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        Text = '16'
      end
      object ComboBox3: TComboBox
        Left = 48
        Top = 12
        Width = 97
        Height = 21
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ItemHeight = 13
        ParentFont = False
        TabOrder = 0
        Text = '     -'
      end
    end
    object VrDemoButton2: TVrDemoButton
      Left = 257
      Top = 671
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Help'
      Color = clMedGray
      TabOrder = 9
    end
    object VrDemoButton3: TVrDemoButton
      Left = 249
      Top = 479
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Reset'
      Color = clMedGray
      TabOrder = 10
    end
  end
end
