object FrmHal109: TFrmHal109
  Left = 628
  Top = 136
  Width = 358
  Height = 527
  VertScrollBar.Position = 107
  Caption = 'Hal 109'
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = -107
    Width = 329
    Height = 600
    Color = clMedGray
    TabOrder = 0
    object Label1: TLabel
      Left = 16
      Top = 11
      Width = 42
      Height = 13
      Alignment = taCenter
      Caption = 'Target:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label2: TLabel
      Left = 64
      Top = 11
      Width = 48
      Height = 13
      Alignment = taCenter
      Caption = '2  1234'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label3: TLabel
      Left = 32
      Top = 27
      Width = 26
      Height = 13
      Alignment = taCenter
      Caption = 'Env:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label4: TLabel
      Left = 64
      Top = 27
      Width = 27
      Height = 13
      Alignment = taCenter
      Caption = 'Surf'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label5: TLabel
      Left = 144
      Top = 11
      Width = 41
      Height = 13
      Alignment = taCenter
      Caption = 'Status:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label6: TLabel
      Left = 152
      Top = 27
      Width = 33
      Height = 13
      Alignment = taCenter
      Caption = 'Avail:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label7: TLabel
      Left = 192
      Top = 11
      Width = 113
      Height = 13
      Alignment = taCenter
      AutoSize = False
      Caption = 'Free generation'
      Color = clGreen
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label8: TLabel
      Left = 192
      Top = 27
      Width = 113
      Height = 13
      Alignment = taCenter
      AutoSize = False
      Caption = 'Available'
      Color = clGreen
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label9: TLabel
      Left = 9
      Top = 51
      Width = 50
      Height = 13
      Alignment = taCenter
      Caption = 'Def env:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel1: TBevel
      Left = 0
      Top = 80
      Width = 329
      Height = 2
    end
    object Label10: TLabel
      Left = 9
      Top = 91
      Width = 41
      Height = 13
      Alignment = taCenter
      Caption = 'K-band'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label14: TLabel
      Left = 9
      Top = 147
      Width = 46
      Height = 13
      Alignment = taCenter
      Caption = 'Director'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label25: TLabel
      Left = 176
      Top = 179
      Width = 129
      Height = 13
      Alignment = taCenter
      AutoSize = False
      Caption = 'Radar no rad zone'
      Color = clRed
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label26: TLabel
      Left = 176
      Top = 195
      Width = 129
      Height = 13
      Alignment = taCenter
      AutoSize = False
      Caption = 'Multiple target'
      Color = clRed
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label27: TLabel
      Left = 176
      Top = 211
      Width = 129
      Height = 13
      Alignment = taCenter
      AutoSize = False
      Caption = 'Track on missile'
      Color = clRed
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label28: TLabel
      Left = 176
      Top = 227
      Width = 129
      Height = 13
      Alignment = taCenter
      AutoSize = False
      Caption = 'Possible kill'
      Color = clOlive
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label29: TLabel
      Left = 9
      Top = 254
      Width = 60
      Height = 13
      Alignment = taCenter
      Caption = 'Rng jump:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label30: TLabel
      Left = 121
      Top = 255
      Width = 19
      Height = 13
      Alignment = taCenter
      Caption = 'yrd'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel2: TBevel
      Left = 0
      Top = 280
      Width = 329
      Height = 2
    end
    object Label31: TLabel
      Left = 45
      Top = 292
      Width = 8
      Height = 13
      Alignment = taCenter
      Caption = 'Z'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label32: TLabel
      Left = 45
      Top = 363
      Width = 8
      Height = 13
      Alignment = taCenter
      Caption = 'Z'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label33: TLabel
      Left = 30
      Top = 337
      Width = 7
      Height = 13
      Alignment = taCenter
      Caption = '1'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label34: TLabel
      Left = 48
      Top = 382
      Width = 56
      Height = 13
      Alignment = taCenter
      Caption = '-1000 yrd'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label35: TLabel
      Left = 248
      Top = 382
      Width = 60
      Height = 13
      Alignment = taCenter
      Caption = '+1000 yrd'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel3: TBevel
      Left = 0
      Top = 408
      Width = 329
      Height = 2
    end
    object Label37: TLabel
      Left = 9
      Top = 487
      Width = 61
      Height = 13
      Alignment = taCenter
      Caption = 'Track gate'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel4: TBevel
      Left = 8
      Top = 552
      Width = 329
      Height = 2
    end
    object ComboBox1: TComboBox
      Left = 64
      Top = 48
      Width = 89
      Height = 21
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ItemHeight = 13
      ParentFont = False
      TabOrder = 0
      Text = '     -'
    end
    object Edit1: TEdit
      Left = 72
      Top = 250
      Width = 41
      Height = 21
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      Text = '200'
    end
    object VrPowerButton2: TVrPowerButton
      Left = 178
      Top = 248
      Width = 127
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Caption = 'TOJ enabled'
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
    end
    object GroupBox1: TGroupBox
      Left = 8
      Top = 102
      Width = 297
      Height = 43
      TabOrder = 3
      object Label11: TLabel
        Left = 8
        Top = 19
        Width = 89
        Height = 13
        Alignment = taCenter
        AutoSize = False
        Caption = 'Tx auth'
        Color = clGreen
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
      end
      object Label12: TLabel
        Left = 104
        Top = 19
        Width = 89
        Height = 13
        Alignment = taCenter
        AutoSize = False
        Caption = 'Radiating'
        Color = clGreen
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
      end
      object Label13: TLabel
        Left = 200
        Top = 19
        Width = 89
        Height = 13
        Alignment = taCenter
        AutoSize = False
        Caption = 'Jammed'
        Color = clRed
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
      end
    end
    object GroupBox2: TGroupBox
      Left = 8
      Top = 158
      Width = 161
      Height = 83
      TabOrder = 4
      object Label15: TLabel
        Left = 17
        Top = 19
        Width = 25
        Height = 13
        Alignment = taCenter
        Caption = 'Brn:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label16: TLabel
        Left = 14
        Top = 37
        Width = 29
        Height = 13
        Alignment = taCenter
        Caption = 'Elev:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label17: TLabel
        Left = 17
        Top = 55
        Width = 27
        Height = 13
        Alignment = taCenter
        Caption = 'Rng:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label18: TLabel
        Left = 48
        Top = 19
        Width = 36
        Height = 13
        Alignment = taCenter
        Caption = '000.0'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object Label19: TLabel
        Left = 48
        Top = 38
        Width = 42
        Height = 13
        Alignment = taCenter
        Caption = '-000.0'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object Label20: TLabel
        Left = 48
        Top = 57
        Width = 40
        Height = 13
        Alignment = taCenter
        Caption = '00000'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object Label21: TLabel
        Left = 96
        Top = 56
        Width = 19
        Height = 13
        Alignment = taCenter
        Caption = 'yrd'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label22: TLabel
        Left = 128
        Top = 19
        Width = 27
        Height = 13
        Alignment = taCenter
        Caption = 'K-bj'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object Label23: TLabel
        Left = 129
        Top = 38
        Width = 16
        Height = 13
        Alignment = taCenter
        Caption = 'TV'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object Label24: TLabel
        Left = 129
        Top = 57
        Width = 22
        Height = 13
        Alignment = taCenter
        Caption = 'K-b'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
      end
    end
    object VrTrackBar1: TVrTrackBar
      Left = 40
      Top = 305
      Width = 17
      Height = 57
      MaxValue = 10
      Position = 1
      Orientation = voVertical
      GutterBevel.InnerShadow = clBtnShadow
      GutterBevel.InnerHighlight = clBtnHighlight
      GutterBevel.InnerWidth = 1
      GutterBevel.InnerStyle = bsNone
      GutterBevel.InnerSpace = 0
      GutterBevel.InnerColor = clBtnFace
      GutterBevel.OuterShadow = clBtnShadow
      GutterBevel.OuterHighlight = clBtnHighlight
      GutterBevel.OuterStyle = bsLowered
      GutterBevel.OuterOutline = osNone
      GutterColor = clGray
      TickColor = clMedGray
      TabOrder = 5
    end
    object GroupBox3: TGroupBox
      Left = 72
      Top = 296
      Width = 233
      Height = 81
      Color = clGreen
      ParentColor = False
      TabOrder = 6
    end
    object VrPowerButton1: TVrPowerButton
      Left = 10
      Top = 416
      Width = 103
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Caption = 'TV camera'
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 7
    end
    object GroupBox4: TGroupBox
      Left = 8
      Top = 442
      Width = 145
      Height = 41
      TabOrder = 8
      object Label36: TLabel
        Left = 6
        Top = 15
        Width = 28
        Height = 13
        Alignment = taCenter
        Caption = 'FOV:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object ComboBox2: TComboBox
        Left = 40
        Top = 12
        Width = 97
        Height = 21
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ItemHeight = 13
        ParentFont = False
        TabOrder = 0
        Text = '     -'
      end
    end
    object VrPowerButton3: TVrPowerButton
      Left = 162
      Top = 456
      Width = 63
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Caption = 'Wiper'
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 9
    end
    object VrDemoButton1: TVrDemoButton
      Left = 241
      Top = 455
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Spray'
      Color = clMedGray
      TabOrder = 10
    end
    object GroupBox5: TGroupBox
      Left = 8
      Top = 498
      Width = 321
      Height = 41
      TabOrder = 11
      object Label38: TLabel
        Left = 6
        Top = 15
        Width = 35
        Height = 13
        Alignment = taCenter
        Caption = 'Mode:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label39: TLabel
        Left = 150
        Top = 15
        Width = 29
        Height = 13
        Alignment = taCenter
        Caption = 'Size:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object VrSpinner1: TVrSpinner
        Left = 184
        Top = 10
        Width = 97
        Height = 25
        Orientation = voHorizontal
        Palette.Low = clMaroon
        Palette.High = clWhite
        TabOrder = 2
      end
      object Edit2: TEdit
        Left = 217
        Top = 12
        Width = 26
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        Text = '16'
      end
      object ComboBox3: TComboBox
        Left = 48
        Top = 12
        Width = 97
        Height = 21
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ItemHeight = 13
        ParentFont = False
        TabOrder = 0
        Text = '     -'
      end
    end
    object VrDemoButton2: TVrDemoButton
      Left = 257
      Top = 567
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Help'
      Color = clMedGray
      TabOrder = 12
    end
  end
end
