object FrmHal39: TFrmHal39
  Left = 254
  Top = 150
  Width = 696
  Height = 127
  HorzScrollBar.Position = 762
  Caption = 'HAL 39'
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = -762
    Top = 0
    Width = 1450
    Height = 73
    Color = clMedGray
    TabOrder = 0
    object GroupBox1: TGroupBox
      Left = 21
      Top = 2
      Width = 356
      Height = 63
      TabOrder = 0
      object Label1: TLabel
        Left = 10
        Top = 14
        Width = 30
        Height = 13
        Alignment = taCenter
        Caption = 'GMT:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label2: TLabel
        Left = 10
        Top = 38
        Width = 34
        Height = 13
        Alignment = taCenter
        Caption = 'Local:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object VrClock1: TVrClock
        Left = 56
        Top = 37
        Width = 49
        Height = 17
        Threaded = True
        Palette.Low = clBlack
        Palette.High = clWhite
        Style = ns7x13
        Color = clMedGray
        ParentColor = False
      end
      object VrClock2: TVrClock
        Left = 56
        Top = 13
        Width = 49
        Height = 17
        Threaded = True
        Palette.Low = clBlack
        Palette.High = clWhite
        Style = ns7x13
        Color = clMedGray
        ParentColor = False
      end
      object DateTimePicker1: TDateTimePicker
        Left = 120
        Top = 12
        Width = 225
        Height = 21
        CalColors.MonthBackColor = clMedGray
        Date = 39356.577526574070000000
        Time = 39356.577526574070000000
        Color = clMedGray
        DateFormat = dfLong
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
    end
    object GroupBox2: TGroupBox
      Left = 381
      Top = 2
      Width = 212
      Height = 63
      TabOrder = 1
      object Label3: TLabel
        Left = 10
        Top = 14
        Width = 99
        Height = 13
        Alignment = taCenter
        Caption = 'Own position Lat:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label4: TLabel
        Left = 10
        Top = 38
        Width = 107
        Height = 13
        Alignment = taCenter
        Caption = 'Geo Grid      Long:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object StaticText1: TStaticText
        Left = 127
        Top = 14
        Width = 67
        Height = 17
        Caption = '00-00.00 N'
        Color = clGreen
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
        TabOrder = 0
      end
      object StaticText2: TStaticText
        Left = 127
        Top = 38
        Width = 73
        Height = 17
        Caption = '000-00.00 E'
        Color = clGreen
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
        TabOrder = 1
      end
    end
    object GroupBox3: TGroupBox
      Left = 597
      Top = 3
      Width = 148
      Height = 63
      TabOrder = 2
      object Label5: TLabel
        Left = 10
        Top = 14
        Width = 39
        Height = 13
        Alignment = taCenter
        Caption = 'Rel OS'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label6: TLabel
        Left = 60
        Top = 14
        Width = 25
        Height = 13
        Alignment = taCenter
        Caption = 'Crs:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label7: TLabel
        Left = 58
        Top = 30
        Width = 27
        Height = 13
        Alignment = taCenter
        Caption = 'Spd:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label8: TLabel
        Left = 124
        Top = 34
        Width = 17
        Height = 13
        Alignment = taCenter
        Caption = 'kts'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object StaticText3: TStaticText
        Left = 87
        Top = 14
        Width = 25
        Height = 17
        Caption = '000'
        Color = clGreen
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
        TabOrder = 0
      end
      object StaticText4: TStaticText
        Left = 87
        Top = 32
        Width = 22
        Height = 17
        Caption = '0.0'
        Color = clGreen
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
        TabOrder = 1
      end
    end
    object GroupBox4: TGroupBox
      Left = 749
      Top = 2
      Width = 143
      Height = 63
      TabOrder = 3
      object Label9: TLabel
        Left = 10
        Top = 14
        Width = 26
        Height = 13
        Alignment = taCenter
        Caption = 'Roll:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label10: TLabel
        Left = 10
        Top = 33
        Width = 32
        Height = 13
        Alignment = taCenter
        Caption = 'Pitch:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label11: TLabel
        Left = 58
        Top = 14
        Width = 39
        Height = 13
        Alignment = taCenter
        Caption = 'Depth:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label12: TLabel
        Left = 122
        Top = 14
        Width = 15
        Height = 13
        Alignment = taCenter
        Caption = 'dft'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object StaticText5: TStaticText
        Left = 103
        Top = 14
        Width = 11
        Height = 17
        Caption = '0'
        Color = clGreen
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
        TabOrder = 0
      end
    end
    object GroupBox5: TGroupBox
      Left = 896
      Top = 2
      Width = 148
      Height = 63
      TabOrder = 4
      object Label13: TLabel
        Left = 10
        Top = 14
        Width = 25
        Height = 13
        Alignment = taCenter
        Caption = 'Drift'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label14: TLabel
        Left = 60
        Top = 14
        Width = 25
        Height = 13
        Alignment = taCenter
        Caption = 'Crs:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label15: TLabel
        Left = 58
        Top = 30
        Width = 27
        Height = 13
        Alignment = taCenter
        Caption = 'Spd:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label16: TLabel
        Left = 124
        Top = 34
        Width = 17
        Height = 13
        Alignment = taCenter
        Caption = 'kts'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object StaticText6: TStaticText
        Left = 87
        Top = 14
        Width = 25
        Height = 17
        Caption = '000'
        Color = clGreen
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
        TabOrder = 0
      end
      object StaticText7: TStaticText
        Left = 87
        Top = 32
        Width = 22
        Height = 17
        Caption = '0.0'
        Color = clGreen
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
        TabOrder = 1
      end
    end
    object GroupBox6: TGroupBox
      Left = 1049
      Top = 2
      Width = 154
      Height = 63
      TabOrder = 5
      object Label17: TLabel
        Left = 10
        Top = 14
        Width = 56
        Height = 13
        Alignment = taCenter
        Caption = 'True wind'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label18: TLabel
        Left = 76
        Top = 14
        Width = 22
        Height = 13
        Alignment = taCenter
        Caption = 'Dir:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label19: TLabel
        Left = 75
        Top = 32
        Width = 27
        Height = 13
        Alignment = taCenter
        Caption = 'Spd:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label20: TLabel
        Left = 134
        Top = 34
        Width = 17
        Height = 13
        Alignment = taCenter
        Caption = 'kts'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object StaticText8: TStaticText
        Left = 105
        Top = 14
        Width = 25
        Height = 17
        Caption = '180'
        Color = clGreen
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
        TabOrder = 0
      end
      object StaticText9: TStaticText
        Left = 105
        Top = 32
        Width = 22
        Height = 17
        Caption = '0.0'
        Color = clGreen
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
        TabOrder = 1
      end
    end
    object GroupBox7: TGroupBox
      Left = 1207
      Top = 2
      Width = 234
      Height = 63
      TabOrder = 6
      object Label21: TLabel
        Left = 10
        Top = 14
        Width = 43
        Height = 13
        Alignment = taCenter
        Caption = 'Barom:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label22: TLabel
        Left = 12
        Top = 38
        Width = 52
        Height = 13
        Alignment = taCenter
        Caption = 'Mag Var:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label23: TLabel
        Left = 123
        Top = 16
        Width = 57
        Height = 13
        Alignment = taCenter
        Caption = 'Air Temp:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label24: TLabel
        Left = 122
        Top = 37
        Width = 55
        Height = 13
        Alignment = taCenter
        Caption = 'Humidity:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object StaticText10: TStaticText
        Left = 73
        Top = 14
        Width = 32
        Height = 17
        Caption = '1013'
        Color = clGreen
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
        TabOrder = 0
      end
      object StaticText11: TStaticText
        Left = 83
        Top = 35
        Width = 22
        Height = 17
        Caption = '0 E'
        Color = clGreen
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentColor = False
        ParentFont = False
        TabOrder = 1
      end
    end
  end
  object StaticText12: TStaticText
    Left = 627
    Top = 19
    Width = 31
    Height = 17
    Caption = '20 C'
    Color = clGreen
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -11
    Font.Name = 'Verdana'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    TabOrder = 1
  end
  object StaticText13: TStaticText
    Left = 627
    Top = 40
    Width = 23
    Height = 17
    Caption = '0%'
    Color = clGreen
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -11
    Font.Name = 'Verdana'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    TabOrder = 2
  end
end
