object FrmHal61: TFrmHal61
  Left = 385
  Top = 123
  Width = 149
  Height = 480
  Caption = 'Hal 61'
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 121
    Height = 923
    Color = clMedGray
    TabOrder = 0
    object Label1: TLabel
      Left = 11
      Top = 334
      Width = 40
      Height = 13
      Alignment = taCenter
      Caption = 'Source'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label2: TLabel
      Left = 10
      Top = 478
      Width = 52
      Height = 13
      Alignment = taCenter
      Caption = 'Selection'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label3: TLabel
      Left = 10
      Top = 220
      Width = 61
      Height = 13
      Alignment = taCenter
      Caption = 'Track type'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel2: TBevel
      Left = -1
      Top = 847
      Width = 123
      Height = 2
    end
    object VrDemoButton1: TVrDemoButton
      Left = 4
      Top = 856
      Width = 56
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Reset'
      Color = clMedGray
      TabOrder = 0
    end
    object VrDemoButton2: TVrDemoButton
      Left = 63
      Top = 856
      Width = 56
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Default'
      Color = clMedGray
      TabOrder = 1
    end
    object GroupBox1: TGroupBox
      Left = 8
      Top = 8
      Width = 97
      Height = 209
      TabOrder = 2
      object VrPowerButton1: TVrPowerButton
        Left = 7
        Top = 11
        Width = 82
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Unknown'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object VrPowerButton2: TVrPowerButton
        Left = 8
        Top = 39
        Width = 68
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Friend'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object VrPowerButton3: TVrPowerButton
        Left = 8
        Top = 67
        Width = 83
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Asd Frnd'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
      object VrPowerButton4: TVrPowerButton
        Left = 8
        Top = 95
        Width = 73
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Pending'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
      end
      object VrPowerButton5: TVrPowerButton
        Left = 8
        Top = 122
        Width = 73
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Neutral'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 4
      end
      object VrPowerButton6: TVrPowerButton
        Left = 7
        Top = 149
        Width = 78
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Suspect'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 5
      end
      object VrPowerButton7: TVrPowerButton
        Left = 7
        Top = 176
        Width = 75
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Hostile'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 6
      end
    end
    object GroupBox2: TGroupBox
      Left = 8
      Top = 346
      Width = 97
      Height = 127
      TabOrder = 3
      object VrPowerButton8: TVrPowerButton
        Left = 4
        Top = 11
        Width = 90
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Automatic'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object VrPowerButton9: TVrPowerButton
        Left = 7
        Top = 92
        Width = 58
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Lost'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object VrPowerButton10: TVrPowerButton
        Left = 5
        Top = 38
        Width = 75
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Manual'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
      object VrPowerButton11: TVrPowerButton
        Left = 5
        Top = 65
        Width = 60
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'LRO'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
      end
    end
    object VrDemoButton3: TVrDemoButton
      Left = 28
      Top = 888
      Width = 56
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Quit'
      Color = clMedGray
      TabOrder = 4
    end
    object GroupBox3: TGroupBox
      Left = 8
      Top = 233
      Width = 97
      Height = 96
      TabOrder = 5
      object VrPowerButton12: TVrPowerButton
        Left = 7
        Top = 11
        Width = 82
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Pnt track'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object VrPowerButton13: TVrPowerButton
        Left = 7
        Top = 39
        Width = 81
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Brn track'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object VrPowerButton14: TVrPowerButton
        Left = 7
        Top = 67
        Width = 74
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Red pnt'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
    end
    object GroupBox4: TGroupBox
      Left = 8
      Top = 491
      Width = 97
      Height = 342
      TabOrder = 6
      object VrPowerButton15: TVrPowerButton
        Left = 4
        Top = 11
        Width = 77
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Symbol'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object VrPowerButton16: TVrPowerButton
        Left = 5
        Top = 92
        Width = 69
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Source'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object VrPowerButton17: TVrPowerButton
        Left = 5
        Top = 38
        Width = 71
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Leader'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
      object VrPowerButton18: TVrPowerButton
        Left = 5
        Top = 65
        Width = 72
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'History'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
      end
      object VrPowerButton19: TVrPowerButton
        Left = 4
        Top = 119
        Width = 49
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'TN'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 4
      end
      object VrPowerButton20: TVrPowerButton
        Left = 5
        Top = 146
        Width = 88
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Link status'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 5
      end
      object VrPowerButton21: TVrPowerButton
        Left = 5
        Top = 173
        Width = 61
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Pu Nr'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 6
      end
      object VrPowerButton22: TVrPowerButton
        Left = 5
        Top = 200
        Width = 69
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Amplif'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 7
      end
      object VrPowerButton23: TVrPowerButton
        Left = 4
        Top = 227
        Width = 71
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Prif co'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 8
      end
      object VrPowerButton24: TVrPowerButton
        Left = 5
        Top = 254
        Width = 80
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Connect'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 9
      end
      object VrPowerButton25: TVrPowerButton
        Left = 5
        Top = 281
        Width = 75
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Info IFF'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 10
      end
      object VrPowerButton26: TVrPowerButton
        Left = 5
        Top = 308
        Width = 84
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Threat nr'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 11
      end
    end
  end
end
