object FrmLinkY_filters: TFrmLinkY_filters
  Left = 192
  Top = 114
  Width = 406
  Height = 480
  VertScrollBar.Position = 129
  Caption = 'Link-Y filters'
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = -129
    Width = 377
    Height = 575
    Color = clMedGray
    TabOrder = 0
    object Label1: TLabel
      Left = 14
      Top = 11
      Width = 61
      Height = 13
      Alignment = taCenter
      Caption = 'Track type'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label2: TLabel
      Left = 198
      Top = 11
      Width = 41
      Height = 13
      Alignment = taCenter
      Caption = 'Special'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label3: TLabel
      Left = 14
      Top = 131
      Width = 44
      Height = 13
      Alignment = taCenter
      Caption = 'Identity'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label4: TLabel
      Left = 14
      Top = 227
      Width = 36
      Height = 13
      Alignment = taCenter
      Caption = 'Range'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label5: TLabel
      Left = 198
      Top = 227
      Width = 43
      Height = 13
      Alignment = taCenter
      Caption = 'Sectors'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label8: TLabel
      Left = 14
      Top = 323
      Width = 33
      Height = 13
      Alignment = taCenter
      Caption = 'Areas'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel1: TBevel
      Left = 0
      Top = 520
      Width = 377
      Height = 2
    end
    object GroupBox1: TGroupBox
      Left = 8
      Top = 24
      Width = 170
      Height = 97
      TabOrder = 0
      object VrPowerButton1: TVrPowerButton
        Left = 6
        Top = 11
        Width = 102
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Point tracks'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object VrPowerButton2: TVrPowerButton
        Left = 6
        Top = 39
        Width = 115
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Bearing tracks'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object VrPowerButton3: TVrPowerButton
        Left = 6
        Top = 67
        Width = 88
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Ref points'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
    end
    object GroupBox2: TGroupBox
      Left = 192
      Top = 25
      Width = 170
      Height = 97
      TabOrder = 1
      object VrPowerButton4: TVrPowerButton
        Left = 6
        Top = 11
        Width = 102
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Non-mil air'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object VrPowerButton5: TVrPowerButton
        Left = 6
        Top = 39
        Width = 107
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Non-mil surf'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object VrPowerButton6: TVrPowerButton
        Left = 6
        Top = 67
        Width = 59
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'NRT'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
    end
    object VrDemoButton5: TVrDemoButton
      Left = 9
      Top = 534
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'OK'
      Color = clMedGray
      TabOrder = 2
    end
    object VrDemoButton1: TVrDemoButton
      Left = 81
      Top = 534
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Apply'
      Color = clMedGray
      TabOrder = 3
    end
    object VrDemoButton2: TVrDemoButton
      Left = 153
      Top = 534
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Reset'
      Color = clMedGray
      TabOrder = 4
    end
    object VrDemoButton3: TVrDemoButton
      Left = 229
      Top = 534
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Cancel'
      Color = clMedGray
      TabOrder = 5
    end
    object VrDemoButton4: TVrDemoButton
      Left = 301
      Top = 534
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Help'
      Color = clMedGray
      TabOrder = 6
    end
    object GroupBox3: TGroupBox
      Left = 8
      Top = 144
      Width = 353
      Height = 73
      TabOrder = 7
      object VrPowerButton7: TVrPowerButton
        Left = 6
        Top = 11
        Width = 91
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Unknown'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object VrPowerButton8: TVrPowerButton
        Left = 6
        Top = 39
        Width = 83
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Pending'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object VrPowerButton9: TVrPowerButton
        Left = 198
        Top = 11
        Width = 107
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Asmd friend'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
      object VrPowerButton10: TVrPowerButton
        Left = 198
        Top = 39
        Width = 75
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Friend'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
      end
    end
    object GroupBox4: TGroupBox
      Left = 8
      Top = 240
      Width = 170
      Height = 73
      TabOrder = 8
      object VrPowerButton11: TVrPowerButton
        Left = 6
        Top = 11
        Width = 51
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Air'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object VrPowerButton12: TVrPowerButton
        Left = 6
        Top = 39
        Width = 77
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Non-air'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object Edit1: TEdit
        Left = 97
        Top = 13
        Width = 32
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        Text = '256'
      end
      object Edit2: TEdit
        Left = 97
        Top = 40
        Width = 32
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
        Text = '256'
      end
    end
    object GroupBox5: TGroupBox
      Left = 192
      Top = 240
      Width = 170
      Height = 73
      TabOrder = 9
      object Label6: TLabel
        Left = 101
        Top = 16
        Width = 5
        Height = 13
        Alignment = taCenter
        Caption = '-'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label7: TLabel
        Left = 107
        Top = 41
        Width = 5
        Height = 13
        Alignment = taCenter
        Caption = '-'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object VrPowerButton13: TVrPowerButton
        Left = 6
        Top = 11
        Width = 51
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = '1'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object VrPowerButton14: TVrPowerButton
        Left = 6
        Top = 39
        Width = 51
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = '2'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object Edit3: TEdit
        Left = 65
        Top = 13
        Width = 32
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        Text = '000'
      end
      object Edit4: TEdit
        Left = 65
        Top = 40
        Width = 32
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
        Text = '000'
      end
      object Edit5: TEdit
        Left = 121
        Top = 13
        Width = 32
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 4
        Text = '000'
      end
      object Edit6: TEdit
        Left = 121
        Top = 40
        Width = 32
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 5
        Text = '000'
      end
    end
    object GroupBox6: TGroupBox
      Left = 8
      Top = 336
      Width = 353
      Height = 169
      TabOrder = 10
      object Label9: TLabel
        Left = 102
        Top = 12
        Width = 56
        Height = 13
        Alignment = taCenter
        Caption = 'Lower left'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label10: TLabel
        Left = 71
        Top = 42
        Width = 22
        Height = 13
        Alignment = taCenter
        Caption = 'Lat:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label11: TLabel
        Left = 61
        Top = 69
        Width = 32
        Height = 13
        Alignment = taCenter
        Caption = 'Long:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label12: TLabel
        Left = 206
        Top = 12
        Width = 64
        Height = 13
        Alignment = taCenter
        Caption = 'Upper right'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label13: TLabel
        Left = 71
        Top = 111
        Width = 22
        Height = 13
        Alignment = taCenter
        Caption = 'Lat:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label14: TLabel
        Left = 61
        Top = 138
        Width = 32
        Height = 13
        Alignment = taCenter
        Caption = 'Long:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object VrPowerButton15: TVrPowerButton
        Left = 6
        Top = 35
        Width = 51
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = '1'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object VrPowerButton16: TVrPowerButton
        Left = 6
        Top = 103
        Width = 51
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = '2'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object Edit7: TEdit
        Left = 97
        Top = 38
        Width = 80
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        Text = '00-00.00 N'
      end
      object Edit8: TEdit
        Left = 97
        Top = 68
        Width = 88
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
        Text = '000-00.00 W'
      end
      object Edit9: TEdit
        Left = 201
        Top = 38
        Width = 80
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 4
        Text = '00-00.00 N'
      end
      object Edit10: TEdit
        Left = 201
        Top = 68
        Width = 88
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 5
        Text = '000-00.00 W'
      end
      object Edit11: TEdit
        Left = 97
        Top = 107
        Width = 80
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 6
        Text = '00-00.00 N'
      end
      object Edit12: TEdit
        Left = 97
        Top = 137
        Width = 88
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 7
        Text = '000-00.00 W'
      end
      object Edit13: TEdit
        Left = 201
        Top = 107
        Width = 80
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 8
        Text = '00-00.00 N'
      end
      object Edit14: TEdit
        Left = 201
        Top = 137
        Width = 88
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 9
        Text = '000-00.00 W'
      end
    end
  end
end
