object FrmMK46_engagement: TFrmMK46_engagement
  Left = 408
  Top = 165
  Width = 318
  Height = 597
  Caption = 'MK46 engagement'
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 307
    Height = 561
    Color = clMedGray
    TabOrder = 0
    object Label1: TLabel
      Left = 27
      Top = 9
      Width = 42
      Height = 13
      Alignment = taCenter
      Caption = 'Target:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel1: TBevel
      Left = 2
      Top = 29
      Width = 315
      Height = 2
    end
    object Label5: TLabel
      Left = 192
      Top = 8
      Width = 105
      Height = 13
      Alignment = taCenter
      AutoSize = False
      Caption = 'Not engageable'
      Color = clRed
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label6: TLabel
      Left = 16
      Top = 75
      Width = 56
      Height = 13
      Alignment = taCenter
      Caption = 'Att angle:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel2: TBevel
      Left = 1
      Top = 175
      Width = 306
      Height = 2
    end
    object Label10: TLabel
      Left = 28
      Top = 43
      Width = 42
      Height = 13
      Alignment = taCenter
      Caption = 'All rng:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label11: TLabel
      Left = 115
      Top = 44
      Width = 26
      Height = 13
      Alignment = taCenter
      Caption = 'kyrd'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label12: TLabel
      Left = 32
      Top = 101
      Width = 39
      Height = 13
      Alignment = taCenter
      Caption = 'Offset:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label2: TLabel
      Left = 197
      Top = 77
      Width = 35
      Height = 13
      Alignment = taCenter
      Caption = 'Mode:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label3: TLabel
      Left = 197
      Top = 101
      Width = 36
      Height = 13
      Alignment = taCenter
      Caption = 'Lnchr:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label4: TLabel
      Left = 112
      Top = 153
      Width = 17
      Height = 13
      Alignment = taCenter
      Caption = 'kts'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label7: TLabel
      Left = 16
      Top = 185
      Width = 77
      Height = 13
      Alignment = taCenter
      Caption = 'Actual results'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label26: TLabel
      Left = 16
      Top = 252
      Width = 19
      Height = 13
      Alignment = taCenter
      Caption = 'EIP'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label27: TLabel
      Left = 168
      Top = 252
      Width = 38
      Height = 13
      Alignment = taCenter
      Caption = 'Advice'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel3: TBevel
      Left = 1
      Top = 327
      Width = 306
      Height = 2
    end
    object Label31: TLabel
      Left = 24
      Top = 340
      Width = 15
      Height = 13
      Alignment = taCenter
      Caption = 'PU'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label32: TLabel
      Left = 258
      Top = 340
      Width = 19
      Height = 13
      Alignment = taCenter
      Caption = 'Sto'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label33: TLabel
      Left = 80
      Top = 356
      Width = 129
      Height = 13
      Alignment = taCenter
      AutoSize = False
      Caption = 'Speed to low'
      Color = clOlive
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Bevel4: TBevel
      Left = 1
      Top = 447
      Width = 306
      Height = 2
    end
    object Bevel5: TBevel
      Left = 1
      Top = 519
      Width = 306
      Height = 2
    end
    object Label34: TLabel
      Left = 16
      Top = 466
      Width = 42
      Height = 13
      Alignment = taCenter
      Caption = 'Target:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label35: TLabel
      Left = 16
      Top = 492
      Width = 42
      Height = 13
      Alignment = taCenter
      Caption = 'Target:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label36: TLabel
      Left = 64
      Top = 466
      Width = 40
      Height = 13
      Alignment = taCenter
      Caption = 'U 1234'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label37: TLabel
      Left = 64
      Top = 493
      Width = 40
      Height = 13
      Alignment = taCenter
      Caption = 'U 1234'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label38: TLabel
      Left = 144
      Top = 466
      Width = 36
      Height = 13
      Alignment = taCenter
      Caption = 'T-run:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label39: TLabel
      Left = 144
      Top = 493
      Width = 36
      Height = 13
      Alignment = taCenter
      Caption = 'T-run:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label40: TLabel
      Left = 184
      Top = 466
      Width = 32
      Height = 13
      Alignment = taCenter
      Caption = '00 00'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label41: TLabel
      Left = 184
      Top = 493
      Width = 32
      Height = 13
      Alignment = taCenter
      Caption = '00 00'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object VrDemoButton5: TVrDemoButton
      Left = 9
      Top = 529
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Quit'
      Color = clMedGray
      TabOrder = 0
    end
    object VrDemoButton6: TVrDemoButton
      Left = 233
      Top = 529
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Help'
      Color = clMedGray
      TabOrder = 1
    end
    object Edit1: TEdit
      Left = 76
      Top = 5
      Width = 65
      Height = 21
      AutoSize = False
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      Text = 'u 1234'
    end
    object Edit6: TEdit
      Left = 74
      Top = 42
      Width = 37
      Height = 21
      AutoSize = False
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      Text = '7.0'
    end
    object GroupBox4: TGroupBox
      Left = 7
      Top = 196
      Width = 290
      Height = 51
      TabOrder = 4
      object Label15: TLabel
        Left = 21
        Top = 12
        Width = 44
        Height = 13
        Alignment = taCenter
        Caption = 'Att rng:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label16: TLabel
        Left = 8
        Top = 30
        Width = 56
        Height = 13
        Alignment = taCenter
        Caption = 'Att angle:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label17: TLabel
        Left = 104
        Top = 14
        Width = 26
        Height = 13
        Alignment = taCenter
        Caption = 'kyrd'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label8: TLabel
        Left = 149
        Top = 13
        Width = 57
        Height = 13
        Alignment = taCenter
        Caption = 'Off angle:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label9: TLabel
        Left = 149
        Top = 30
        Width = 57
        Height = 13
        Alignment = taCenter
        Caption = 'Launcher:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label13: TLabel
        Left = 69
        Top = 14
        Width = 25
        Height = 13
        Alignment = taCenter
        Caption = '00.0'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label14: TLabel
        Left = 69
        Top = 30
        Width = 21
        Height = 13
        Alignment = taCenter
        Caption = '000'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label21: TLabel
        Left = 213
        Top = 14
        Width = 25
        Height = 13
        Alignment = taCenter
        Caption = '00.0'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label25: TLabel
        Left = 213
        Top = 30
        Width = 17
        Height = 13
        Alignment = taCenter
        Caption = 'stb'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
    end
    object GroupBox5: TGroupBox
      Left = 9
      Top = 268
      Width = 144
      Height = 51
      TabOrder = 5
      object Label18: TLabel
        Left = 8
        Top = 12
        Width = 28
        Height = 13
        Alignment = taCenter
        Caption = 'TTG:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label19: TLabel
        Left = 8
        Top = 30
        Width = 29
        Height = 13
        Alignment = taCenter
        Caption = 'RTG:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label20: TLabel
        Left = 40
        Top = 14
        Width = 51
        Height = 13
        Alignment = taCenter
        Caption = '00:00 00'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label30: TLabel
        Left = 40
        Top = 30
        Width = 25
        Height = 13
        Alignment = taCenter
        Caption = '00.0'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
    end
    object GroupBox6: TGroupBox
      Left = 168
      Top = 268
      Width = 129
      Height = 51
      TabOrder = 6
      object Label22: TLabel
        Left = 8
        Top = 12
        Width = 29
        Height = 13
        Alignment = taCenter
        Caption = 'CTS:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label23: TLabel
        Left = 8
        Top = 30
        Width = 27
        Height = 13
        Alignment = taCenter
        Caption = 'Spd:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label24: TLabel
        Left = 80
        Top = 30
        Width = 17
        Height = 13
        Alignment = taCenter
        Caption = 'kts'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label28: TLabel
        Left = 40
        Top = 13
        Width = 21
        Height = 13
        Alignment = taCenter
        Caption = '000'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label29: TLabel
        Left = 40
        Top = 29
        Width = 14
        Height = 13
        Alignment = taCenter
        Caption = '00'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
    end
    object ComboBox1: TComboBox
      Left = 74
      Top = 72
      Width = 63
      Height = 21
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ItemHeight = 13
      ParentFont = False
      TabOrder = 7
      Text = '45'
    end
    object ComboBox2: TComboBox
      Left = 74
      Top = 98
      Width = 63
      Height = 21
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ItemHeight = 13
      ParentFont = False
      TabOrder = 8
      Text = '0'
    end
    object RadioButton1: TRadioButton
      Left = 15
      Top = 124
      Width = 58
      Height = 17
      Caption = 'Durat'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 9
    end
    object ComboBox3: TComboBox
      Left = 234
      Top = 74
      Width = 63
      Height = 21
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ItemHeight = 13
      ParentFont = False
      TabOrder = 10
      Text = 'Urgent'
    end
    object ComboBox4: TComboBox
      Left = 234
      Top = 99
      Width = 63
      Height = 21
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ItemHeight = 13
      ParentFont = False
      TabOrder = 11
      Text = 'Auto'
    end
    object Edit2: TEdit
      Left = 74
      Top = 125
      Width = 65
      Height = 21
      AutoSize = False
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 12
      Text = '00:10 00'
    end
    object RadioButton2: TRadioButton
      Left = 15
      Top = 148
      Width = 50
      Height = 17
      Caption = 'Spd'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 13
    end
    object Edit3: TEdit
      Left = 74
      Top = 149
      Width = 31
      Height = 21
      AutoSize = False
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 14
      Text = '10'
    end
    object VrDemoButton1: TVrDemoButton
      Left = 208
      Top = 144
      Width = 89
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Designate'
      Color = clMedGray
      TabOrder = 15
    end
    object VrDemoButton2: TVrDemoButton
      Left = 81
      Top = 377
      Width = 128
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Confirm launch'
      Color = clMedGray
      TabOrder = 16
    end
    object VrDemoButton3: TVrDemoButton
      Left = 257
      Top = 361
      Width = 24
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Color = clOlive
      TabOrder = 17
    end
    object VrDemoButton4: TVrDemoButton
      Left = 19
      Top = 361
      Width = 24
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Color = clOlive
      TabOrder = 18
    end
    object VrDemoButton7: TVrDemoButton
      Left = 19
      Top = 389
      Width = 24
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Color = clOlive
      TabOrder = 19
    end
    object VrDemoButton8: TVrDemoButton
      Left = 19
      Top = 417
      Width = 24
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Color = clOlive
      TabOrder = 20
    end
    object VrDemoButton9: TVrDemoButton
      Left = 257
      Top = 389
      Width = 24
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Color = clGreen
      TabOrder = 21
    end
    object VrDemoButton10: TVrDemoButton
      Left = 257
      Top = 417
      Width = 24
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Color = clGreen
      TabOrder = 22
    end
    object VrDemoButton11: TVrDemoButton
      Left = 233
      Top = 456
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Stop'
      Color = clMedGray
      TabOrder = 23
    end
    object VrDemoButton12: TVrDemoButton
      Left = 233
      Top = 488
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Stop'
      Color = clMedGray
      TabOrder = 24
    end
  end
end
