object FrmNaval_gunfire_supportHal156: TFrmNaval_gunfire_supportHal156
  Left = 100
  Top = 7
  Width = 373
  Height = 480
  Caption = 'Naval Gunfire Support'
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 361
    Height = 441
    Color = clMedGray
    TabOrder = 0
    object Label1: TLabel
      Left = 16
      Top = 12
      Width = 108
      Height = 13
      Alignment = taCenter
      Caption = 'Bombardm. mode:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel1: TBevel
      Left = 0
      Top = 40
      Width = 361
      Height = 2
    end
    object Label2: TLabel
      Left = 8
      Top = 52
      Width = 93
      Height = 13
      Alignment = taCenter
      Caption = 'Tgt engagement'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label3: TLabel
      Left = 8
      Top = 225
      Width = 119
      Height = 13
      Alignment = taCenter
      Caption = 'Current engagement'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label4: TLabel
      Left = 176
      Top = 284
      Width = 66
      Height = 13
      Alignment = taCenter
      Caption = 'NGS Target'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel2: TBevel
      Left = 0
      Top = 400
      Width = 361
      Height = 2
    end
    object Label21: TLabel
      Left = 16
      Top = 251
      Width = 47
      Height = 13
      Alignment = taCenter
      Caption = 'Tgt pos:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label22: TLabel
      Left = 176
      Top = 251
      Width = 37
      Height = 13
      Alignment = taCenter
      Caption = 'Tgt id:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label23: TLabel
      Left = 217
      Top = 251
      Width = 8
      Height = 13
      Alignment = taCenter
      Caption = '9'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label24: TLabel
      Left = 8
      Top = 284
      Width = 110
      Height = 13
      Alignment = taCenter
      Caption = 'Target geo position'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel3: TBevel
      Left = 0
      Top = 216
      Width = 361
      Height = 2
    end
    object VrPowerButton1: TVrPowerButton
      Left = 248
      Top = 7
      Width = 89
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Caption = 'Active'
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
    end
    object ComboBox1: TComboBox
      Left = 136
      Top = 8
      Width = 89
      Height = 21
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ItemHeight = 13
      ParentFont = False
      TabOrder = 1
      Text = 'Blind'
    end
    object ComboBox2: TComboBox
      Left = 72
      Top = 249
      Width = 57
      Height = 21
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ItemHeight = 13
      ParentFont = False
      TabOrder = 2
      Text = 'Geo'
    end
    object GroupBox1: TGroupBox
      Left = 8
      Top = 299
      Width = 161
      Height = 94
      TabOrder = 3
      object Label5: TLabel
        Left = 18
        Top = 20
        Width = 22
        Height = 13
        Alignment = taCenter
        Caption = 'Lat:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label25: TLabel
        Left = 8
        Top = 44
        Width = 32
        Height = 13
        Alignment = taCenter
        Caption = 'Long:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label6: TLabel
        Left = 8
        Top = 68
        Width = 31
        Height = 13
        Alignment = taCenter
        Caption = 'Hght:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label26: TLabel
        Left = 96
        Top = 68
        Width = 8
        Height = 13
        Alignment = taCenter
        Caption = 'ft'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Edit1: TEdit
        Left = 48
        Top = 16
        Width = 73
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        Text = '00-00.00 N'
      end
      object Edit2: TEdit
        Left = 48
        Top = 40
        Width = 81
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        Text = '000-00.00 E'
      end
      object Edit3: TEdit
        Left = 48
        Top = 64
        Width = 41
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        Text = '0000'
      end
    end
    object GroupBox2: TGroupBox
      Left = 176
      Top = 299
      Width = 169
      Height = 94
      TabOrder = 4
      object Label7: TLabel
        Left = 24
        Top = 36
        Width = 27
        Height = 13
        Alignment = taCenter
        Caption = 'Rng:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label8: TLabel
        Left = 120
        Top = 36
        Width = 19
        Height = 13
        Alignment = taCenter
        Caption = 'yrd'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label9: TLabel
        Left = 24
        Top = 17
        Width = 25
        Height = 13
        Alignment = taCenter
        Caption = 'Brn:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label10: TLabel
        Left = 20
        Top = 60
        Width = 31
        Height = 13
        Alignment = taCenter
        Caption = 'Hght:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label11: TLabel
        Left = 120
        Top = 60
        Width = 8
        Height = 13
        Alignment = taCenter
        Caption = 'ft'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label12: TLabel
        Left = 64
        Top = 18
        Width = 36
        Height = 13
        Alignment = taCenter
        Caption = '000.0'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object Label13: TLabel
        Left = 64
        Top = 37
        Width = 40
        Height = 13
        Alignment = taCenter
        Caption = '00000'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object Label14: TLabel
        Left = 64
        Top = 61
        Width = 32
        Height = 13
        Alignment = taCenter
        Caption = '0000'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
      end
    end
    object VrDemoButton1: TVrDemoButton
      Left = 9
      Top = 408
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Quit'
      Color = clMedGray
      TabOrder = 5
    end
    object VrDemoButton2: TVrDemoButton
      Left = 289
      Top = 408
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Help'
      Color = clMedGray
      TabOrder = 6
    end
    object GroupBox3: TGroupBox
      Left = 8
      Top = 66
      Width = 337
      Height = 135
      TabOrder = 7
      object Label15: TLabel
        Left = 8
        Top = 12
        Width = 12
        Height = 13
        Alignment = taCenter
        Caption = 'TI'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label16: TLabel
        Left = 48
        Top = 12
        Width = 20
        Height = 13
        Alignment = taCenter
        Caption = 'Brn'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label17: TLabel
        Left = 96
        Top = 12
        Width = 22
        Height = 13
        Alignment = taCenter
        Caption = 'Rng'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label18: TLabel
        Left = 152
        Top = 12
        Width = 26
        Height = 13
        Alignment = taCenter
        Caption = 'Hght'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label19: TLabel
        Left = 216
        Top = 12
        Width = 20
        Height = 13
        Alignment = taCenter
        Caption = 'Pos'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label20: TLabel
        Left = 272
        Top = 12
        Width = 24
        Height = 13
        Alignment = taCenter
        Caption = 'ENG'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object ListBox1: TListBox
        Left = 8
        Top = 32
        Width = 313
        Height = 65
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ItemHeight = 13
        Items.Strings = (
          '1       359.9    32000     10000       UTM         NENG'
          '2'
          '3'
          '4')
        ParentFont = False
        TabOrder = 0
      end
      object VrDemoButton3: TVrDemoButton
        Left = 9
        Top = 104
        Width = 64
        Height = 25
        FontEnter.Charset = DEFAULT_CHARSET
        FontEnter.Color = clWhite
        FontEnter.Height = -11
        FontEnter.Name = 'Verdana'
        FontEnter.Style = [fsBold]
        FontLeave.Charset = DEFAULT_CHARSET
        FontLeave.Color = clWhite
        FontLeave.Height = -11
        FontLeave.Name = 'Verdana'
        FontLeave.Style = [fsBold]
        Caption = 'Next'
        Color = clMedGray
        TabOrder = 1
      end
      object VrDemoButton4: TVrDemoButton
        Left = 137
        Top = 104
        Width = 64
        Height = 25
        FontEnter.Charset = DEFAULT_CHARSET
        FontEnter.Color = clWhite
        FontEnter.Height = -11
        FontEnter.Name = 'Verdana'
        FontEnter.Style = [fsBold]
        FontLeave.Charset = DEFAULT_CHARSET
        FontLeave.Color = clWhite
        FontLeave.Height = -11
        FontLeave.Name = 'Verdana'
        FontLeave.Style = [fsBold]
        Caption = 'Delete'
        Color = clMedGray
        TabOrder = 2
      end
      object VrDemoButton5: TVrDemoButton
        Left = 257
        Top = 104
        Width = 64
        Height = 25
        FontEnter.Charset = DEFAULT_CHARSET
        FontEnter.Color = clWhite
        FontEnter.Height = -11
        FontEnter.Name = 'Verdana'
        FontEnter.Style = [fsBold]
        FontLeave.Charset = DEFAULT_CHARSET
        FontLeave.Color = clWhite
        FontLeave.Height = -11
        FontLeave.Name = 'Verdana'
        FontLeave.Style = [fsBold]
        Caption = 'Plan ...'
        Color = clMedGray
        TabOrder = 3
      end
    end
  end
end
