object FrmNaval_gunfire_support: TFrmNaval_gunfire_support
  Left = 347
  Top = 253
  Width = 373
  Height = 283
  Caption = 'Naval Gunfire Support'
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 361
    Height = 249
    Color = clMedGray
    TabOrder = 0
    object Label1: TLabel
      Left = 16
      Top = 12
      Width = 108
      Height = 13
      Alignment = taCenter
      Caption = 'Bombardm. mode:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel1: TBevel
      Left = 0
      Top = 40
      Width = 361
      Height = 2
    end
    object Label2: TLabel
      Left = 16
      Top = 52
      Width = 49
      Height = 13
      Alignment = taCenter
      Caption = 'Tracker:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label3: TLabel
      Left = 16
      Top = 84
      Width = 37
      Height = 13
      Alignment = taCenter
      Caption = 'Target'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label4: TLabel
      Left = 184
      Top = 84
      Width = 66
      Height = 13
      Alignment = taCenter
      Caption = 'NGS Target'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel2: TBevel
      Left = 0
      Top = 208
      Width = 361
      Height = 2
    end
    object VrPowerButton1: TVrPowerButton
      Left = 248
      Top = 7
      Width = 89
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Caption = 'Active'
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
    end
    object ComboBox1: TComboBox
      Left = 136
      Top = 8
      Width = 89
      Height = 21
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ItemHeight = 13
      ParentFont = False
      TabOrder = 1
      Text = 'Direct'
    end
    object ComboBox2: TComboBox
      Left = 72
      Top = 48
      Width = 89
      Height = 21
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ItemHeight = 13
      ParentFont = False
      TabOrder = 2
      Text = '      -'
    end
    object GroupBox1: TGroupBox
      Left = 8
      Top = 99
      Width = 161
      Height = 46
      TabOrder = 3
      object Label5: TLabel
        Left = 16
        Top = 20
        Width = 27
        Height = 13
        Alignment = taCenter
        Caption = 'Rng:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label6: TLabel
        Left = 112
        Top = 20
        Width = 19
        Height = 13
        Alignment = taCenter
        Caption = 'yrd'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Edit1: TEdit
        Left = 48
        Top = 16
        Width = 49
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        Text = '00000'
      end
    end
    object GroupBox2: TGroupBox
      Left = 176
      Top = 99
      Width = 169
      Height = 94
      TabOrder = 4
      object Label7: TLabel
        Left = 24
        Top = 36
        Width = 27
        Height = 13
        Alignment = taCenter
        Caption = 'Rng:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label8: TLabel
        Left = 120
        Top = 36
        Width = 19
        Height = 13
        Alignment = taCenter
        Caption = 'yrd'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label9: TLabel
        Left = 24
        Top = 17
        Width = 25
        Height = 13
        Alignment = taCenter
        Caption = 'Brn:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label10: TLabel
        Left = 20
        Top = 60
        Width = 31
        Height = 13
        Alignment = taCenter
        Caption = 'Hght:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label11: TLabel
        Left = 120
        Top = 60
        Width = 8
        Height = 13
        Alignment = taCenter
        Caption = 'ft'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label12: TLabel
        Left = 64
        Top = 18
        Width = 36
        Height = 13
        Alignment = taCenter
        Caption = '000.0'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object Label13: TLabel
        Left = 64
        Top = 37
        Width = 40
        Height = 13
        Alignment = taCenter
        Caption = '00000'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object Label14: TLabel
        Left = 64
        Top = 61
        Width = 32
        Height = 13
        Alignment = taCenter
        Caption = '0000'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
      end
    end
    object VrDemoButton1: TVrDemoButton
      Left = 9
      Top = 216
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Quit'
      Color = clMedGray
      TabOrder = 5
    end
    object VrDemoButton2: TVrDemoButton
      Left = 289
      Top = 216
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Help'
      Color = clMedGray
      TabOrder = 6
    end
  end
end
