object FrmNavigation_route: TFrmNavigation_route
  Left = 373
  Top = 113
  Width = 318
  Height = 428
  Caption = 'Navigation route'
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 307
    Height = 393
    Color = clMedGray
    TabOrder = 0
    object Label1: TLabel
      Left = 152
      Top = 220
      Width = 99
      Height = 13
      Alignment = taCenter
      Caption = 'Cross track error'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel1: TBevel
      Left = -6
      Top = 151
      Width = 315
      Height = 2
    end
    object Bevel2: TBevel
      Left = 1
      Top = 343
      Width = 306
      Height = 2
    end
    object Label12: TLabel
      Left = 8
      Top = 156
      Width = 53
      Height = 13
      Alignment = taCenter
      Caption = 'Next turn'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label13: TLabel
      Left = 157
      Top = 155
      Width = 70
      Height = 13
      Alignment = taCenter
      Caption = 'End of route'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label21: TLabel
      Left = 8
      Top = 219
      Width = 38
      Height = 13
      Alignment = taCenter
      Caption = 'Advice'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object GroupBox1: TGroupBox
      Left = 8
      Top = 57
      Width = 289
      Height = 88
      TabOrder = 0
      object Label4: TLabel
        Left = 240
        Top = 60
        Width = 17
        Height = 13
        Alignment = taCenter
        Caption = 'kts'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label10: TLabel
        Left = 136
        Top = 12
        Width = 57
        Height = 13
        Alignment = taCenter
        Caption = 'Tum rate:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label11: TLabel
        Left = 235
        Top = 12
        Width = 32
        Height = 13
        Alignment = taCenter
        Caption = 'deg/s'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Edit2: TEdit
        Left = 195
        Top = 33
        Width = 78
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object Edit3: TEdit
        Left = 195
        Top = 58
        Width = 30
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        Text = '1'
      end
      object RadioButton1: TRadioButton
        Left = 135
        Top = 36
        Width = 50
        Height = 17
        Caption = 'ETA:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
      object RadioButton2: TRadioButton
        Left = 136
        Top = 60
        Width = 49
        Height = 17
        Caption = 'Spd:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
      end
      object Edit4: TEdit
        Left = 195
        Top = 9
        Width = 38
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 4
      end
      object VrPowerButton4: TVrPowerButton
        Left = 5
        Top = 10
        Width = 68
        Height = 22
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Active'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 5
      end
      object VrPowerButton1: TVrPowerButton
        Left = 5
        Top = 34
        Width = 99
        Height = 22
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Safety alert'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 6
      end
      object VrPowerButton2: TVrPowerButton
        Left = 5
        Top = 58
        Width = 79
        Height = 22
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Reverse'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 7
      end
    end
    object VrDemoButton5: TVrDemoButton
      Left = 9
      Top = 353
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Quit'
      Color = clMedGray
      TabOrder = 1
    end
    object VrDemoButton6: TVrDemoButton
      Left = 241
      Top = 353
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Help'
      Color = clMedGray
      TabOrder = 2
    end
    object Edit1: TEdit
      Left = 9
      Top = 35
      Width = 189
      Height = 21
      AutoSize = False
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
    end
    object GroupBox4: TGroupBox
      Left = 7
      Top = 167
      Width = 138
      Height = 51
      TabOrder = 4
      object Label15: TLabel
        Left = 8
        Top = 12
        Width = 28
        Height = 13
        Alignment = taCenter
        Caption = 'TTG:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label16: TLabel
        Left = 8
        Top = 30
        Width = 29
        Height = 13
        Alignment = taCenter
        Caption = 'RTG:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label17: TLabel
        Left = 104
        Top = 30
        Width = 17
        Height = 13
        Alignment = taCenter
        Caption = 'NM'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
    end
    object GroupBox5: TGroupBox
      Left = 152
      Top = 167
      Width = 144
      Height = 51
      TabOrder = 5
      object Label18: TLabel
        Left = 8
        Top = 12
        Width = 27
        Height = 13
        Alignment = taCenter
        Caption = 'ETA:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label19: TLabel
        Left = 8
        Top = 30
        Width = 29
        Height = 13
        Alignment = taCenter
        Caption = 'RTG:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label20: TLabel
        Left = 104
        Top = 30
        Width = 17
        Height = 13
        Alignment = taCenter
        Caption = 'NM'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
    end
    object GroupBox6: TGroupBox
      Left = 7
      Top = 231
      Width = 138
      Height = 51
      TabOrder = 6
      object Label22: TLabel
        Left = 8
        Top = 12
        Width = 25
        Height = 13
        Alignment = taCenter
        Caption = 'Crs:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label23: TLabel
        Left = 8
        Top = 30
        Width = 27
        Height = 13
        Alignment = taCenter
        Caption = 'Spd:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label24: TLabel
        Left = 80
        Top = 30
        Width = 17
        Height = 13
        Alignment = taCenter
        Caption = 'kts'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
    end
    object GroupBox2: TGroupBox
      Left = 151
      Top = 231
      Width = 138
      Height = 51
      TabOrder = 7
      object Label2: TLabel
        Left = 8
        Top = 12
        Width = 27
        Height = 13
        Alignment = taCenter
        Caption = 'Rng:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label3: TLabel
        Left = 8
        Top = 30
        Width = 30
        Height = 13
        Alignment = taCenter
        Caption = 'Side:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label7: TLabel
        Left = 104
        Top = 14
        Width = 19
        Height = 13
        Alignment = taCenter
        Caption = 'yrd'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
    end
    object GroupBox3: TGroupBox
      Left = 7
      Top = 284
      Width = 138
      Height = 51
      TabOrder = 8
      object Label5: TLabel
        Left = 40
        Top = 12
        Width = 52
        Height = 13
        Alignment = taCenter
        Caption = 'Safety Pt'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label6: TLabel
        Left = 80
        Top = 30
        Width = 19
        Height = 13
        Alignment = taCenter
        Caption = 'yrd'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
    end
    object GroupBox7: TGroupBox
      Left = 151
      Top = 284
      Width = 138
      Height = 51
      TabOrder = 9
      object Label8: TLabel
        Left = 40
        Top = 12
        Width = 60
        Height = 13
        Alignment = taCenter
        Caption = 'Safety Stb'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label9: TLabel
        Left = 88
        Top = 30
        Width = 19
        Height = 13
        Alignment = taCenter
        Caption = 'yrd'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
    end
    object VrDemoButton1: TVrDemoButton
      Left = 10
      Top = 5
      Width = 186
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Prepare routes ...'
      Color = clMedGray
      TabOrder = 10
    end
    object VrDemoButton2: TVrDemoButton
      Left = 205
      Top = 5
      Width = 93
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Select ...'
      Color = clMedGray
      TabOrder = 11
    end
  end
end
