object FrmOp_desk: TFrmOp_desk
  Left = 607
  Top = 162
  Width = 315
  Height = 335
  Caption = 'Operator Desk'
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 305
    Height = 297
    Color = clMedGray
    TabOrder = 0
    object Label1: TLabel
      Left = 8
      Top = 11
      Width = 78
      Height = 13
      Alignment = taCenter
      Caption = 'Timer Status:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel2: TBevel
      Left = 1
      Top = 165
      Width = 305
      Height = 2
    end
    object Bevel1: TBevel
      Left = 0
      Top = 253
      Width = 305
      Height = 2
    end
    object VrDemoButton5: TVrDemoButton
      Left = 105
      Top = 264
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'OK'
      Color = clMedGray
      TabOrder = 0
    end
    object VrDemoButton6: TVrDemoButton
      Left = 313
      Top = 296
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Help'
      Color = clMedGray
      TabOrder = 1
    end
    object GroupBox1: TGroupBox
      Left = 8
      Top = 24
      Width = 281
      Height = 129
      TabOrder = 2
      object VrClock1: TVrClock
        Left = 32
        Top = 16
        Width = 73
        Height = 17
        Threaded = True
        Palette.Low = clBlack
        Palette.High = clWhite
        Style = ns7x13
        Color = clMedGray
        ParentColor = False
      end
      object VrClock2: TVrClock
        Left = 32
        Top = 56
        Width = 73
        Height = 17
        Threaded = True
        Palette.Low = clBlack
        Palette.High = clWhite
        Style = ns7x13
        Color = clMedGray
        ParentColor = False
      end
      object VrClock3: TVrClock
        Left = 32
        Top = 96
        Width = 73
        Height = 17
        Threaded = True
        Palette.Low = clBlack
        Palette.High = clWhite
        Style = ns7x13
        Color = clMedGray
        ParentColor = False
      end
      object VrDemoButton1: TVrDemoButton
        Left = 145
        Top = 16
        Width = 120
        Height = 25
        FontEnter.Charset = DEFAULT_CHARSET
        FontEnter.Color = clWhite
        FontEnter.Height = -11
        FontEnter.Name = 'Verdana'
        FontEnter.Style = [fsBold]
        FontLeave.Charset = DEFAULT_CHARSET
        FontLeave.Color = clWhite
        FontLeave.Height = -11
        FontLeave.Name = 'Verdana'
        FontLeave.Style = [fsBold]
        Caption = 'Set Timer 1'
        Color = clMedGray
        TabOrder = 0
      end
      object VrDemoButton2: TVrDemoButton
        Left = 145
        Top = 56
        Width = 120
        Height = 25
        FontEnter.Charset = DEFAULT_CHARSET
        FontEnter.Color = clWhite
        FontEnter.Height = -11
        FontEnter.Name = 'Verdana'
        FontEnter.Style = [fsBold]
        FontLeave.Charset = DEFAULT_CHARSET
        FontLeave.Color = clWhite
        FontLeave.Height = -11
        FontLeave.Name = 'Verdana'
        FontLeave.Style = [fsBold]
        Caption = 'Set Timer 2'
        Color = clMedGray
        TabOrder = 1
      end
      object VrDemoButton3: TVrDemoButton
        Left = 145
        Top = 96
        Width = 120
        Height = 25
        FontEnter.Charset = DEFAULT_CHARSET
        FontEnter.Color = clWhite
        FontEnter.Height = -11
        FontEnter.Name = 'Verdana'
        FontEnter.Style = [fsBold]
        FontLeave.Charset = DEFAULT_CHARSET
        FontLeave.Color = clWhite
        FontLeave.Height = -11
        FontLeave.Name = 'Verdana'
        FontLeave.Style = [fsBold]
        Caption = 'Set Timer 3'
        Color = clMedGray
        TabOrder = 2
      end
      object VrPowerButton1: TVrPowerButton
        Left = 11
        Top = 15
        Width = 25
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
      end
      object VrPowerButton2: TVrPowerButton
        Left = 11
        Top = 55
        Width = 25
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 4
      end
      object VrPowerButton3: TVrPowerButton
        Left = 11
        Top = 95
        Width = 25
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 5
      end
    end
    object VrDemoButton9: TVrDemoButton
      Left = 17
      Top = 184
      Width = 112
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Notepad'
      Color = clMedGray
      TabOrder = 3
    end
    object VrDemoButton10: TVrDemoButton
      Left = 145
      Top = 184
      Width = 112
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Bitmap Editor'
      Color = clMedGray
      TabOrder = 4
    end
    object VrDemoButton11: TVrDemoButton
      Left = 17
      Top = 216
      Width = 112
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Calculator'
      Color = clMedGray
      TabOrder = 5
    end
    object ComboBox1: TComboBox
      Left = 145
      Top = 217
      Width = 115
      Height = 21
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ItemHeight = 13
      ParentFont = False
      TabOrder = 6
      Text = 'Snapshot'
    end
  end
end
