object FrmSec_screen: TFrmSec_screen
  Left = 557
  Top = 198
  Width = 316
  Height = 381
  Caption = 'Sector screen'
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 307
    Height = 345
    Color = clMedGray
    TabOrder = 0
    object Label1: TLabel
      Left = 16
      Top = 43
      Width = 34
      Height = 13
      Alignment = taCenter
      Caption = 'Offset'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel1: TBevel
      Left = 2
      Top = 39
      Width = 306
      Height = 2
    end
    object Label5: TLabel
      Left = 152
      Top = 43
      Width = 53
      Height = 13
      Alignment = taCenter
      Caption = 'Warnings'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label6: TLabel
      Left = 168
      Top = 131
      Width = 62
      Height = 13
      Alignment = taCenter
      Caption = 'Seat Track'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel2: TBevel
      Left = 1
      Top = 303
      Width = 306
      Height = 2
    end
    object VrDemoButton1: TVrDemoButton
      Left = 9
      Top = 139
      Width = 128
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Edit screen...'
      Color = clMedGray
      TabOrder = 0
    end
    object GroupBox1: TGroupBox
      Left = 8
      Top = 55
      Width = 129
      Height = 74
      TabOrder = 1
      object Label2: TLabel
        Left = 8
        Top = 21
        Width = 24
        Height = 13
        Alignment = taCenter
        Caption = 'Bm:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label3: TLabel
        Left = 8
        Top = 49
        Width = 27
        Height = 13
        Alignment = taCenter
        Caption = 'Rng:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label4: TLabel
        Left = 74
        Top = 49
        Width = 26
        Height = 13
        Alignment = taCenter
        Caption = 'kyrd'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Edit1: TEdit
        Left = 40
        Top = 18
        Width = 41
        Height = 21
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        Text = '000'
      end
      object Edit2: TEdit
        Left = 40
        Top = 45
        Width = 29
        Height = 21
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        Text = '0'
      end
    end
    object GroupBox2: TGroupBox
      Left = 152
      Top = 56
      Width = 145
      Height = 73
      TabOrder = 2
      object VrPowerButton4: TVrPowerButton
        Left = 10
        Top = 12
        Width = 103
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Enter sector'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object VrPowerButton5: TVrPowerButton
        Left = 10
        Top = 40
        Width = 95
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Exit sector'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
    end
    object VrDemoButton2: TVrDemoButton
      Left = 9
      Top = 169
      Width = 128
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Use new screen'
      Color = clMedGray
      TabOrder = 3
    end
    object VrPowerButton2: TVrPowerButton
      Left = 10
      Top = 240
      Width = 127
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Caption = 'Rotation slaved'
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
    end
    object VrPowerButton3: TVrPowerButton
      Left = 10
      Top = 272
      Width = 127
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Caption = 'Active'
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 5
    end
    object VrDemoButton3: TVrDemoButton
      Left = 161
      Top = 273
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Apply'
      Color = clMedGray
      TabOrder = 6
    end
    object VrDemoButton4: TVrDemoButton
      Left = 233
      Top = 273
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Remove'
      Color = clMedGray
      TabOrder = 7
    end
    object VrDemoButton5: TVrDemoButton
      Left = 9
      Top = 313
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Quit'
      Color = clMedGray
      TabOrder = 8
    end
    object VrDemoButton6: TVrDemoButton
      Left = 241
      Top = 313
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Help'
      Color = clMedGray
      TabOrder = 9
    end
    object ComboBox1: TComboBox
      Left = 8
      Top = 8
      Width = 89
      Height = 21
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ItemHeight = 13
      ParentFont = False
      TabOrder = 10
      Text = 'Own ship'
    end
    object Edit3: TEdit
      Left = 160
      Top = 146
      Width = 129
      Height = 92
      AutoSize = False
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 11
    end
    object Edit4: TEdit
      Left = 184
      Top = 243
      Width = 73
      Height = 21
      AutoSize = False
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 12
    end
  end
end
