object FrmSnapshot: TFrmSnapshot
  Left = 524
  Top = 292
  Width = 405
  Height = 261
  Caption = 'Snapshot'
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 393
    Height = 225
    Color = clMedGray
    TabOrder = 0
    object Bevel1: TBevel
      Left = 2
      Top = 183
      Width = 391
      Height = 2
    end
    object GroupBox1: TGroupBox
      Left = 11
      Top = 0
      Width = 374
      Height = 73
      TabOrder = 0
      object Label3: TLabel
        Left = 17
        Top = 44
        Width = 148
        Height = 13
        Alignment = taCenter
        Caption = 'Image sequence number:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Edit1: TEdit
        Left = 169
        Top = 42
        Width = 40
        Height = 21
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        Text = '001'
      end
      object VrPowerButton1: TVrPowerButton
        Left = 10
        Top = 11
        Width = 126
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'hide while grab'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object VrPowerButton2: TVrPowerButton
        Left = 162
        Top = 11
        Width = 151
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'always Rootwindow'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
    end
    object Edit2: TEdit
      Left = 17
      Top = 85
      Width = 256
      Height = 92
      AutoSize = False
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      Text = 'Image-0-000.bmp'
    end
    object VrDemoButton3: TVrDemoButton
      Left = 288
      Top = 87
      Width = 89
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Grab'
      Color = clMedGray
      TabOrder = 2
    end
    object VrDemoButton4: TVrDemoButton
      Left = 288
      Top = 119
      Width = 89
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'View'
      Color = clMedGray
      TabOrder = 3
    end
    object VrDemoButton5: TVrDemoButton
      Left = 288
      Top = 151
      Width = 89
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Delete'
      Color = clMedGray
      TabOrder = 4
    end
    object VrDemoButton6: TVrDemoButton
      Left = 8
      Top = 191
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Quit'
      Color = clMedGray
      TabOrder = 5
    end
    object VrDemoButton7: TVrDemoButton
      Left = 327
      Top = 191
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Help'
      Color = clMedGray
      TabOrder = 6
    end
  end
end
