object FrmStationing: TFrmStationing
  Left = 183
  Top = 133
  Width = 318
  Height = 435
  Caption = 'Stationing'
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 307
    Height = 401
    Color = clMedGray
    TabOrder = 0
    object Label1: TLabel
      Left = 8
      Top = 9
      Width = 40
      Height = 13
      Alignment = taCenter
      Caption = 'Station'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel1: TBevel
      Left = -6
      Top = 213
      Width = 315
      Height = 2
    end
    object Label5: TLabel
      Left = 160
      Top = 8
      Width = 38
      Height = 13
      Alignment = taCenter
      Caption = 'Guide:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label6: TLabel
      Left = 160
      Top = 139
      Width = 30
      Height = 13
      Alignment = taCenter
      Caption = 'Mode'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel2: TBevel
      Left = 1
      Top = 359
      Width = 306
      Height = 2
    end
    object Label10: TLabel
      Left = 8
      Top = 139
      Width = 57
      Height = 13
      Alignment = taCenter
      Caption = 'Tum rate:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label11: TLabel
      Left = 107
      Top = 140
      Width = 32
      Height = 13
      Alignment = taCenter
      Caption = 'deg/s'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label12: TLabel
      Left = 8
      Top = 219
      Width = 40
      Height = 13
      Alignment = taCenter
      Caption = 'Station'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label13: TLabel
      Left = 152
      Top = 219
      Width = 58
      Height = 13
      Alignment = taCenter
      Caption = 'Turn point'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label21: TLabel
      Left = 88
      Top = 291
      Width = 38
      Height = 13
      Alignment = taCenter
      Caption = 'Advice'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object VrPowerButton1: TVrPowerButton
      Left = 8
      Top = 183
      Width = 89
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Caption = 'Active'
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
    end
    object GroupBox1: TGroupBox
      Left = 8
      Top = 25
      Width = 129
      Height = 105
      TabOrder = 1
      object Label2: TLabel
        Left = 16
        Top = 51
        Width = 24
        Height = 13
        Alignment = taCenter
        Caption = 'Bm:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label3: TLabel
        Left = 16
        Top = 75
        Width = 27
        Height = 13
        Alignment = taCenter
        Caption = 'Rng:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label4: TLabel
        Left = 104
        Top = 76
        Width = 17
        Height = 13
        Alignment = taCenter
        Caption = 'NM'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Edit2: TEdit
        Left = 43
        Top = 49
        Width = 38
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object Edit3: TEdit
        Left = 43
        Top = 74
        Width = 57
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object RadioButton1: TRadioButton
        Left = 7
        Top = 12
        Width = 73
        Height = 17
        Caption = 'Relative'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
      object RadioButton2: TRadioButton
        Left = 7
        Top = 28
        Width = 73
        Height = 17
        Caption = 'Absolute'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
      end
    end
    object GroupBox2: TGroupBox
      Left = 152
      Top = 26
      Width = 145
      Height = 103
      TabOrder = 2
      object Label7: TLabel
        Left = 16
        Top = 51
        Width = 25
        Height = 13
        Alignment = taCenter
        Caption = 'Crs:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label8: TLabel
        Left = 16
        Top = 75
        Width = 27
        Height = 13
        Alignment = taCenter
        Caption = 'Spd:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label9: TLabel
        Left = 80
        Top = 76
        Width = 17
        Height = 13
        Alignment = taCenter
        Caption = 'kts'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object RadioButton3: TRadioButton
        Left = 7
        Top = 12
        Width = 73
        Height = 17
        Caption = 'Actual'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object RadioButton4: TRadioButton
        Left = 7
        Top = 28
        Width = 73
        Height = 17
        Caption = 'Average'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object Edit4: TEdit
        Left = 43
        Top = 49
        Width = 54
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
      object Edit5: TEdit
        Left = 43
        Top = 74
        Width = 30
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
      end
    end
    object VrDemoButton5: TVrDemoButton
      Left = 9
      Top = 369
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Quit'
      Color = clMedGray
      TabOrder = 3
    end
    object VrDemoButton6: TVrDemoButton
      Left = 241
      Top = 369
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Help'
      Color = clMedGray
      TabOrder = 4
    end
    object Edit1: TEdit
      Left = 201
      Top = 5
      Width = 65
      Height = 21
      AutoSize = False
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 5
    end
    object Edit6: TEdit
      Left = 66
      Top = 138
      Width = 37
      Height = 21
      AutoSize = False
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 6
    end
    object GroupBox3: TGroupBox
      Left = 152
      Top = 151
      Width = 145
      Height = 59
      TabOrder = 7
      object Label14: TLabel
        Left = 104
        Top = 36
        Width = 17
        Height = 13
        Alignment = taCenter
        Caption = 'kts'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object RadioButton5: TRadioButton
        Left = 7
        Top = 12
        Width = 50
        Height = 17
        Caption = 'Dur:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object RadioButton6: TRadioButton
        Left = 7
        Top = 36
        Width = 50
        Height = 17
        Caption = 'Spd:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object Edit7: TEdit
        Left = 59
        Top = 9
        Width = 62
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
      object Edit8: TEdit
        Left = 59
        Top = 34
        Width = 38
        Height = 21
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
      end
    end
    object GroupBox4: TGroupBox
      Left = 7
      Top = 236
      Width = 138
      Height = 51
      TabOrder = 8
      object Label15: TLabel
        Left = 8
        Top = 12
        Width = 28
        Height = 13
        Alignment = taCenter
        Caption = 'TTG:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label16: TLabel
        Left = 8
        Top = 30
        Width = 29
        Height = 13
        Alignment = taCenter
        Caption = 'RTG:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label17: TLabel
        Left = 104
        Top = 30
        Width = 17
        Height = 13
        Alignment = taCenter
        Caption = 'NM'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
    end
    object GroupBox5: TGroupBox
      Left = 153
      Top = 236
      Width = 144
      Height = 51
      TabOrder = 9
      object Label18: TLabel
        Left = 8
        Top = 12
        Width = 28
        Height = 13
        Alignment = taCenter
        Caption = 'TTG:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label19: TLabel
        Left = 8
        Top = 30
        Width = 29
        Height = 13
        Alignment = taCenter
        Caption = 'RTG:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label20: TLabel
        Left = 104
        Top = 30
        Width = 17
        Height = 13
        Alignment = taCenter
        Caption = 'NM'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
    end
    object GroupBox6: TGroupBox
      Left = 87
      Top = 303
      Width = 106
      Height = 51
      TabOrder = 10
      object Label22: TLabel
        Left = 8
        Top = 12
        Width = 25
        Height = 13
        Alignment = taCenter
        Caption = 'Crs:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label23: TLabel
        Left = 8
        Top = 30
        Width = 27
        Height = 13
        Alignment = taCenter
        Caption = 'Spd:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label24: TLabel
        Left = 80
        Top = 30
        Width = 17
        Height = 13
        Alignment = taCenter
        Caption = 'kts'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
    end
  end
end
