object FrmTact_figures: TFrmTact_figures
  Left = 815
  Top = 131
  Width = 134
  Height = 444
  Caption = 'Tact Figures'
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 121
    Height = 409
    Color = clMedGray
    TabOrder = 0
    object Label1: TLabel
      Left = 11
      Top = 10
      Width = 72
      Height = 13
      Alignment = taCenter
      Caption = 'Environment'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label2: TLabel
      Left = 10
      Top = 180
      Width = 64
      Height = 13
      Alignment = taCenter
      Caption = 'Figure type'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel2: TBevel
      Left = -2
      Top = 327
      Width = 123
      Height = 2
    end
    object VrDemoButton1: TVrDemoButton
      Left = 4
      Top = 336
      Width = 56
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Reset'
      Color = clMedGray
      TabOrder = 0
    end
    object VrDemoButton2: TVrDemoButton
      Left = 63
      Top = 336
      Width = 56
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Default'
      Color = clMedGray
      TabOrder = 1
    end
    object GroupBox1: TGroupBox
      Left = 8
      Top = 24
      Width = 97
      Height = 153
      TabOrder = 2
      object VrPowerButton1: TVrPowerButton
        Left = 7
        Top = 11
        Width = 47
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Air'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object VrPowerButton2: TVrPowerButton
        Left = 8
        Top = 39
        Width = 73
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Surface'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object VrPowerButton3: TVrPowerButton
        Left = 8
        Top = 67
        Width = 74
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Subsurf'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
      object VrPowerButton4: TVrPowerButton
        Left = 8
        Top = 95
        Width = 57
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'NGS'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
      end
      object VrPowerButton5: TVrPowerButton
        Left = 8
        Top = 122
        Width = 84
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Unknown'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 4
      end
    end
    object GroupBox2: TGroupBox
      Left = 8
      Top = 193
      Width = 97
      Height = 128
      TabOrder = 3
      object VrPowerButton6: TVrPowerButton
        Left = 7
        Top = 11
        Width = 82
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Engage'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object VrPowerButton7: TVrPowerButton
        Left = 7
        Top = 39
        Width = 75
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Areas'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object VrPowerButton8: TVrPowerButton
        Left = 7
        Top = 67
        Width = 67
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'FOC'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
      object VrPowerButton9: TVrPowerButton
        Left = 7
        Top = 95
        Width = 76
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Miscell'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
      end
    end
    object VrDemoButton3: TVrDemoButton
      Left = 28
      Top = 368
      Width = 56
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Quit'
      Color = clMedGray
      TabOrder = 4
    end
  end
end
