object FrmTDA_com: TFrmTDA_com
  Left = 255
  Top = 108
  Width = 273
  Height = 349
  Caption = 'TDA Composition'
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 265
    Height = 313
    Color = clMedGray
    TabOrder = 0
    object Bevel2: TBevel
      Left = -41
      Top = 263
      Width = 306
      Height = 2
    end
    object Label1: TLabel
      Left = 227
      Top = 2
      Width = 21
      Height = 13
      Alignment = taCenter
      Caption = '100'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label2: TLabel
      Left = 186
      Top = 34
      Width = 14
      Height = 13
      Alignment = taCenter
      Caption = '50'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label3: TLabel
      Left = 210
      Top = 66
      Width = 14
      Height = 13
      Alignment = taCenter
      Caption = '75'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label4: TLabel
      Left = 186
      Top = 98
      Width = 14
      Height = 13
      Alignment = taCenter
      Caption = '50'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label5: TLabel
      Left = 210
      Top = 130
      Width = 14
      Height = 13
      Alignment = taCenter
      Caption = '75'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label6: TLabel
      Left = 210
      Top = 162
      Width = 14
      Height = 13
      Alignment = taCenter
      Caption = '75'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label7: TLabel
      Left = 186
      Top = 194
      Width = 14
      Height = 13
      Alignment = taCenter
      Caption = '50'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label8: TLabel
      Left = 186
      Top = 226
      Width = 14
      Height = 13
      Alignment = taCenter
      Caption = '50'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object VrPowerButton1: TVrPowerButton
      Left = 8
      Top = 39
      Width = 73
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Caption = 'Tracks'
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
    end
    object VrDemoButton5: TVrDemoButton
      Left = 9
      Top = 272
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Quit'
      Color = clMedGray
      TabOrder = 1
    end
    object VrDemoButton1: TVrDemoButton
      Left = 97
      Top = 272
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Reset'
      Color = clMedGray
      TabOrder = 2
    end
    object VrDemoButton2: TVrDemoButton
      Left = 185
      Top = 272
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Default'
      Color = clMedGray
      TabOrder = 3
    end
    object VrPowerButton2: TVrPowerButton
      Left = 8
      Top = 7
      Width = 57
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Caption = 'Grid'
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
    end
    object VrPowerButton3: TVrPowerButton
      Left = 8
      Top = 71
      Width = 97
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Caption = 'Range rings'
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 5
    end
    object VrPowerButton4: TVrPowerButton
      Left = 8
      Top = 103
      Width = 81
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Caption = 'Compass'
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 6
    end
    object VrPowerButton5: TVrPowerButton
      Left = 8
      Top = 135
      Width = 105
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Caption = 'Hdng marker'
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 7
    end
    object VrPowerButton6: TVrPowerButton
      Left = 8
      Top = 167
      Width = 81
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Caption = 'Tact Fig'
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 8
    end
    object VrPowerButton7: TVrPowerButton
      Left = 8
      Top = 199
      Width = 97
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Caption = 'Radar video'
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 9
    end
    object VrPowerButton8: TVrPowerButton
      Left = 8
      Top = 231
      Width = 65
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Caption = 'Maps'
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 10
    end
    object VrTrackBar1: TVrTrackBar
      Left = 128
      Top = 16
      Width = 129
      Height = 17
      Position = 100
      GutterBevel.InnerShadow = clBtnShadow
      GutterBevel.InnerHighlight = clBtnHighlight
      GutterBevel.InnerWidth = 1
      GutterBevel.InnerStyle = bsNone
      GutterBevel.InnerSpace = 0
      GutterBevel.InnerColor = clBtnFace
      GutterBevel.OuterShadow = clBtnShadow
      GutterBevel.OuterHighlight = clBtnHighlight
      GutterBevel.OuterStyle = bsLowered
      GutterBevel.OuterOutline = osNone
      GutterColor = clGray
      TickColor = clMedGray
      TabOrder = 11
    end
    object VrTrackBar2: TVrTrackBar
      Left = 128
      Top = 48
      Width = 129
      Height = 17
      Position = 50
      GutterBevel.InnerShadow = clBtnShadow
      GutterBevel.InnerHighlight = clBtnHighlight
      GutterBevel.InnerWidth = 1
      GutterBevel.InnerStyle = bsNone
      GutterBevel.InnerSpace = 0
      GutterBevel.InnerColor = clBtnFace
      GutterBevel.OuterShadow = clBtnShadow
      GutterBevel.OuterHighlight = clBtnHighlight
      GutterBevel.OuterStyle = bsLowered
      GutterBevel.OuterOutline = osNone
      GutterColor = clGray
      TickColor = clMedGray
      TabOrder = 12
    end
    object VrTrackBar3: TVrTrackBar
      Left = 128
      Top = 80
      Width = 129
      Height = 17
      Position = 75
      GutterBevel.InnerShadow = clBtnShadow
      GutterBevel.InnerHighlight = clBtnHighlight
      GutterBevel.InnerWidth = 1
      GutterBevel.InnerStyle = bsNone
      GutterBevel.InnerSpace = 0
      GutterBevel.InnerColor = clBtnFace
      GutterBevel.OuterShadow = clBtnShadow
      GutterBevel.OuterHighlight = clBtnHighlight
      GutterBevel.OuterStyle = bsLowered
      GutterBevel.OuterOutline = osNone
      GutterColor = clGray
      TickColor = clMedGray
      TabOrder = 13
    end
    object VrTrackBar4: TVrTrackBar
      Left = 128
      Top = 112
      Width = 129
      Height = 17
      Position = 50
      GutterBevel.InnerShadow = clBtnShadow
      GutterBevel.InnerHighlight = clBtnHighlight
      GutterBevel.InnerWidth = 1
      GutterBevel.InnerStyle = bsNone
      GutterBevel.InnerSpace = 0
      GutterBevel.InnerColor = clBtnFace
      GutterBevel.OuterShadow = clBtnShadow
      GutterBevel.OuterHighlight = clBtnHighlight
      GutterBevel.OuterStyle = bsLowered
      GutterBevel.OuterOutline = osNone
      GutterColor = clGray
      TickColor = clMedGray
      TabOrder = 14
    end
    object VrTrackBar5: TVrTrackBar
      Left = 128
      Top = 144
      Width = 129
      Height = 17
      Position = 75
      GutterBevel.InnerShadow = clBtnShadow
      GutterBevel.InnerHighlight = clBtnHighlight
      GutterBevel.InnerWidth = 1
      GutterBevel.InnerStyle = bsNone
      GutterBevel.InnerSpace = 0
      GutterBevel.InnerColor = clBtnFace
      GutterBevel.OuterShadow = clBtnShadow
      GutterBevel.OuterHighlight = clBtnHighlight
      GutterBevel.OuterStyle = bsLowered
      GutterBevel.OuterOutline = osNone
      GutterColor = clGray
      TickColor = clMedGray
      TabOrder = 15
    end
    object VrTrackBar6: TVrTrackBar
      Left = 128
      Top = 176
      Width = 129
      Height = 17
      Position = 75
      GutterBevel.InnerShadow = clBtnShadow
      GutterBevel.InnerHighlight = clBtnHighlight
      GutterBevel.InnerWidth = 1
      GutterBevel.InnerStyle = bsNone
      GutterBevel.InnerSpace = 0
      GutterBevel.InnerColor = clBtnFace
      GutterBevel.OuterShadow = clBtnShadow
      GutterBevel.OuterHighlight = clBtnHighlight
      GutterBevel.OuterStyle = bsLowered
      GutterBevel.OuterOutline = osNone
      GutterColor = clGray
      TickColor = clMedGray
      TabOrder = 16
    end
    object VrTrackBar7: TVrTrackBar
      Left = 128
      Top = 208
      Width = 129
      Height = 17
      Position = 50
      GutterBevel.InnerShadow = clBtnShadow
      GutterBevel.InnerHighlight = clBtnHighlight
      GutterBevel.InnerWidth = 1
      GutterBevel.InnerStyle = bsNone
      GutterBevel.InnerSpace = 0
      GutterBevel.InnerColor = clBtnFace
      GutterBevel.OuterShadow = clBtnShadow
      GutterBevel.OuterHighlight = clBtnHighlight
      GutterBevel.OuterStyle = bsLowered
      GutterBevel.OuterOutline = osNone
      GutterColor = clGray
      TickColor = clMedGray
      TabOrder = 17
    end
    object VrTrackBar8: TVrTrackBar
      Left = 128
      Top = 240
      Width = 129
      Height = 17
      Position = 50
      GutterBevel.InnerShadow = clBtnShadow
      GutterBevel.InnerHighlight = clBtnHighlight
      GutterBevel.InnerWidth = 1
      GutterBevel.InnerStyle = bsNone
      GutterBevel.InnerSpace = 0
      GutterBevel.InnerColor = clBtnFace
      GutterBevel.OuterShadow = clBtnShadow
      GutterBevel.OuterHighlight = clBtnHighlight
      GutterBevel.OuterStyle = bsLowered
      GutterBevel.OuterOutline = osNone
      GutterColor = clGray
      TickColor = clMedGray
      TabOrder = 18
    end
  end
end
