object FrmTrack_selection_air: TFrmTrack_selection_air
  Left = 322
  Top = 237
  Width = 404
  Height = 387
  Caption = 'Track selection air'
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 393
    Height = 353
    Color = clMedGray
    TabOrder = 0
    object Label1: TLabel
      Left = 16
      Top = 12
      Width = 49
      Height = 13
      Alignment = taCenter
      Caption = 'Identity:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label2: TLabel
      Left = 128
      Top = 12
      Width = 62
      Height = 13
      Alignment = taCenter
      Caption = 'Kinematics'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel1: TBevel
      Left = 0
      Top = 178
      Width = 393
      Height = 2
    end
    object Label7: TLabel
      Left = 24
      Top = 188
      Width = 88
      Height = 13
      Alignment = taCenter
      Caption = 'Included tracks'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label8: TLabel
      Left = 272
      Top = 188
      Width = 90
      Height = 13
      Alignment = taCenter
      Caption = 'Excluded tracks'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel2: TBevel
      Left = 0
      Top = 306
      Width = 393
      Height = 2
    end
    object VrDemoButton1: TVrDemoButton
      Left = 137
      Top = 266
      Width = 120
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Auto select'
      Color = clMedGray
      TabOrder = 0
    end
    object GroupBox1: TGroupBox
      Left = 14
      Top = 24
      Width = 107
      Height = 145
      TabOrder = 1
      object VrPowerButton1: TVrPowerButton
        Left = 16
        Top = 15
        Width = 73
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Hostile'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object VrPowerButton2: TVrPowerButton
        Left = 16
        Top = 47
        Width = 73
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Suspect'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object VrPowerButton3: TVrPowerButton
        Left = 16
        Top = 79
        Width = 62
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Unkn'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
      object VrPowerButton4: TVrPowerButton
        Left = 16
        Top = 111
        Width = 73
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Pending'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
      end
    end
    object GroupBox2: TGroupBox
      Left = 128
      Top = 24
      Width = 257
      Height = 145
      TabOrder = 2
      object Label3: TLabel
        Left = 145
        Top = 20
        Width = 5
        Height = 13
        Alignment = taCenter
        Caption = '-'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label4: TLabel
        Left = 145
        Top = 52
        Width = 5
        Height = 13
        Alignment = taCenter
        Caption = '-'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label5: TLabel
        Left = 157
        Top = 84
        Width = 5
        Height = 13
        Alignment = taCenter
        Caption = '-'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object Label6: TLabel
        Left = 227
        Top = 84
        Width = 17
        Height = 13
        Alignment = taCenter
        Caption = 'kts'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
      end
      object VrPowerButton5: TVrPowerButton
        Left = 16
        Top = 15
        Width = 73
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Sector'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object VrPowerButton6: TVrPowerButton
        Left = 16
        Top = 47
        Width = 73
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Range'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object VrPowerButton7: TVrPowerButton
        Left = 16
        Top = 79
        Width = 73
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Speed'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
      object VrPowerButton8: TVrPowerButton
        Left = 16
        Top = 111
        Width = 140
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Inclinication angle'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
      end
      object Edit1: TEdit
        Left = 97
        Top = 15
        Width = 40
        Height = 25
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 4
        Text = '000'
      end
      object Edit2: TEdit
        Left = 157
        Top = 15
        Width = 40
        Height = 25
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 5
        Text = '000'
      end
      object Edit3: TEdit
        Left = 97
        Top = 47
        Width = 40
        Height = 25
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 6
        Text = '000'
      end
      object Edit4: TEdit
        Left = 157
        Top = 47
        Width = 40
        Height = 25
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 7
        Text = '000'
      end
      object Edit5: TEdit
        Left = 97
        Top = 79
        Width = 48
        Height = 25
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 8
        Text = '0000'
      end
      object Edit6: TEdit
        Left = 173
        Top = 79
        Width = 48
        Height = 25
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 9
        Text = '000'
      end
      object Edit7: TEdit
        Left = 165
        Top = 111
        Width = 40
        Height = 25
        AutoSize = False
        Color = clGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 10
        Text = '000'
      end
    end
    object ListBox1: TListBox
      Left = 24
      Top = 205
      Width = 97
      Height = 87
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ItemHeight = 13
      Items.Strings = (
        'A  1 2 3 4'
        '2'
        '3'
        '4'
        '5'
        '')
      ParentFont = False
      TabOrder = 3
    end
    object ListBox2: TListBox
      Left = 272
      Top = 204
      Width = 97
      Height = 87
      Color = clGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ItemHeight = 13
      Items.Strings = (
        'A  1 2 3 4'
        '2'
        '3'
        '4'
        '5'
        '')
      ParentFont = False
      TabOrder = 4
    end
    object VrDemoButton2: TVrDemoButton
      Left = 17
      Top = 319
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'OK'
      Color = clMedGray
      TabOrder = 5
    end
    object VrDemoButton3: TVrDemoButton
      Left = 91
      Top = 319
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Apply'
      Color = clMedGray
      TabOrder = 6
    end
    object VrDemoButton4: TVrDemoButton
      Left = 165
      Top = 319
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Reset'
      Color = clMedGray
      TabOrder = 7
    end
    object VrDemoButton5: TVrDemoButton
      Left = 239
      Top = 319
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Cancel'
      Color = clMedGray
      TabOrder = 8
    end
    object VrDemoButton6: TVrDemoButton
      Left = 313
      Top = 319
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Help'
      Color = clMedGray
      TabOrder = 9
    end
  end
end
