object FrmTrack_filter: TFrmTrack_filter
  Left = 367
  Top = -6
  Width = 131
  Height = 749
  Caption = 'Track filter'
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 121
    Height = 713
    Color = clMedGray
    TabOrder = 0
    object Bevel2: TBevel
      Left = -49
      Top = 671
      Width = 170
      Height = 2
    end
    object Label1: TLabel
      Left = 11
      Top = 10
      Width = 72
      Height = 13
      Alignment = taCenter
      Caption = 'Environment'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label2: TLabel
      Left = 10
      Top = 180
      Width = 61
      Height = 13
      Alignment = taCenter
      Caption = 'Track type'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label3: TLabel
      Left = 10
      Top = 292
      Width = 44
      Height = 13
      Alignment = taCenter
      Caption = 'Identity'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label4: TLabel
      Left = 12
      Top = 487
      Width = 40
      Height = 13
      Alignment = taCenter
      Caption = 'Source'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label5: TLabel
      Left = 36
      Top = 627
      Width = 49
      Height = 13
      Alignment = taCenter
      Caption = 'Symbols'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object VrDemoButton1: TVrDemoButton
      Left = 4
      Top = 680
      Width = 56
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Reset'
      Color = clMedGray
      TabOrder = 0
    end
    object VrDemoButton2: TVrDemoButton
      Left = 63
      Top = 680
      Width = 56
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Default'
      Color = clMedGray
      TabOrder = 1
    end
    object GroupBox1: TGroupBox
      Left = 8
      Top = 24
      Width = 97
      Height = 153
      TabOrder = 2
      object VrPowerButton1: TVrPowerButton
        Left = 7
        Top = 11
        Width = 47
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Air'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object VrPowerButton2: TVrPowerButton
        Left = 8
        Top = 39
        Width = 73
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Surface'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object VrPowerButton3: TVrPowerButton
        Left = 8
        Top = 67
        Width = 74
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Subsurf'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
      object VrPowerButton4: TVrPowerButton
        Left = 8
        Top = 95
        Width = 57
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'NGS'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
      end
      object VrPowerButton5: TVrPowerButton
        Left = 8
        Top = 122
        Width = 84
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Unknown'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 4
      end
    end
    object GroupBox2: TGroupBox
      Left = 8
      Top = 193
      Width = 97
      Height = 96
      TabOrder = 3
      object VrPowerButton6: TVrPowerButton
        Left = 7
        Top = 11
        Width = 82
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Pnt track'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object VrPowerButton7: TVrPowerButton
        Left = 7
        Top = 39
        Width = 81
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Brn track'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object VrPowerButton8: TVrPowerButton
        Left = 7
        Top = 67
        Width = 74
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Red pnt'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
    end
    object GroupBox3: TGroupBox
      Left = 8
      Top = 305
      Width = 97
      Height = 178
      TabOrder = 4
      object VrPowerButton9: TVrPowerButton
        Left = 7
        Top = 11
        Width = 82
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Unknown'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object VrPowerButton10: TVrPowerButton
        Left = 8
        Top = 39
        Width = 65
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Friend'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object VrPowerButton11: TVrPowerButton
        Left = 8
        Top = 67
        Width = 81
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Asd Frnd'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
      object VrPowerButton12: TVrPowerButton
        Left = 8
        Top = 95
        Width = 73
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Pending'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
      end
      object VrPowerButton13: TVrPowerButton
        Left = 8
        Top = 122
        Width = 73
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Neutral'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 4
      end
      object VrPowerButton14: TVrPowerButton
        Left = 8
        Top = 149
        Width = 73
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Suspect'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 5
      end
    end
    object GroupBox4: TGroupBox
      Left = 8
      Top = 500
      Width = 97
      Height = 124
      TabOrder = 5
      object VrPowerButton15: TVrPowerButton
        Left = 7
        Top = 11
        Width = 86
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Automatic'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object VrPowerButton16: TVrPowerButton
        Left = 8
        Top = 39
        Width = 67
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Manual'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object VrPowerButton17: TVrPowerButton
        Left = 8
        Top = 67
        Width = 52
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'LRO'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
      object VrPowerButton18: TVrPowerButton
        Left = 8
        Top = 95
        Width = 53
        Height = 25
        Palette.Low = clGray
        Palette.High = clLime
        Caption = 'Lost'
        Color = clMedGray
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
      end
    end
    object ComboBox1: TComboBox
      Left = 24
      Top = 643
      Width = 73
      Height = 21
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ItemHeight = 13
      ParentFont = False
      TabOrder = 6
      Text = 'Icons'
    end
  end
end
