object Form2: TForm2
  Left = 225
  Top = 63
  Width = 373
  Height = 541
  Caption = 'HAL 40'
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = -2
    Width = 345
    Height = 515
    Color = clMedGray
    TabOrder = 0
    object Label1: TLabel
      Left = 11
      Top = 7
      Width = 85
      Height = 13
      Alignment = taCenter
      Caption = 'Primary video:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel1: TBevel
      Left = 0
      Top = 159
      Width = 344
      Height = 2
    end
    object Label5: TLabel
      Left = 208
      Top = 8
      Width = 65
      Height = 13
      Alignment = taCenter
      Caption = 'Brightness:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label6: TLabel
      Left = 43
      Top = 126
      Width = 55
      Height = 13
      Alignment = taCenter
      Caption = 'Intensity:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel2: TBevel
      Left = 1
      Top = 199
      Width = 344
      Height = 2
    end
    object Label7: TLabel
      Left = 257
      Top = 26
      Width = 14
      Height = 13
      Alignment = taCenter
      Caption = '50'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label8: TLabel
      Left = 257
      Top = 66
      Width = 14
      Height = 13
      Alignment = taCenter
      Caption = '50'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label2: TLabel
      Left = 11
      Top = 171
      Width = 101
      Height = 13
      Alignment = taCenter
      Caption = 'Secondary video:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label3: TLabel
      Left = 11
      Top = 211
      Width = 40
      Height = 13
      Alignment = taCenter
      Caption = 'History'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label4: TLabel
      Left = 51
      Top = 227
      Width = 35
      Height = 13
      Alignment = taCenter
      Caption = 'Mode:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label9: TLabel
      Left = 35
      Top = 275
      Width = 54
      Height = 13
      Alignment = taCenter
      Caption = 'Duration:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label10: TLabel
      Left = 27
      Top = 315
      Width = 61
      Height = 13
      Alignment = taCenter
      Caption = 'Threshold:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label12: TLabel
      Left = 129
      Top = 258
      Width = 7
      Height = 13
      Alignment = taCenter
      Caption = '6'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel3: TBevel
      Left = 0
      Top = 346
      Width = 344
      Height = 2
    end
    object Bevel4: TBevel
      Left = 1
      Top = 386
      Width = 344
      Height = 2
    end
    object Label14: TLabel
      Left = 43
      Top = 435
      Width = 62
      Height = 13
      Alignment = taCenter
      Caption = 'CATV-bus:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Bevel5: TBevel
      Left = 1
      Top = 474
      Width = 344
      Height = 2
    end
    object VrDemoButton3: TVrDemoButton
      Left = 17
      Top = 353
      Width = 144
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Apply defaults'
      Color = clMedGray
      TabOrder = 0
    end
    object VrDemoButton4: TVrDemoButton
      Left = 184
      Top = 353
      Width = 129
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Safe as defaults'
      Color = clMedGray
      TabOrder = 1
    end
    object VrDemoButton5: TVrDemoButton
      Left = 9
      Top = 481
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Quit'
      Color = clMedGray
      TabOrder = 2
    end
    object VrDemoButton6: TVrDemoButton
      Left = 273
      Top = 481
      Width = 64
      Height = 25
      FontEnter.Charset = DEFAULT_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -11
      FontEnter.Name = 'Verdana'
      FontEnter.Style = [fsBold]
      FontLeave.Charset = DEFAULT_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -11
      FontLeave.Name = 'Verdana'
      FontLeave.Style = [fsBold]
      Caption = 'Help'
      Color = clMedGray
      TabOrder = 3
    end
    object VrTrackBar1: TVrTrackBar
      Left = 200
      Top = 40
      Width = 129
      Height = 17
      Position = 50
      GutterBevel.InnerShadow = clBtnShadow
      GutterBevel.InnerHighlight = clBtnHighlight
      GutterBevel.InnerWidth = 1
      GutterBevel.InnerStyle = bsNone
      GutterBevel.InnerSpace = 0
      GutterBevel.InnerColor = clBtnFace
      GutterBevel.OuterShadow = clBtnShadow
      GutterBevel.OuterHighlight = clBtnHighlight
      GutterBevel.OuterStyle = bsLowered
      GutterBevel.OuterOutline = osNone
      GutterColor = clGray
      TickColor = clMedGray
      TabOrder = 4
    end
    object VrTrackBar2: TVrTrackBar
      Left = 200
      Top = 80
      Width = 129
      Height = 17
      Position = 50
      GutterBevel.InnerShadow = clBtnShadow
      GutterBevel.InnerHighlight = clBtnHighlight
      GutterBevel.InnerWidth = 1
      GutterBevel.InnerStyle = bsNone
      GutterBevel.InnerSpace = 0
      GutterBevel.InnerColor = clBtnFace
      GutterBevel.OuterShadow = clBtnShadow
      GutterBevel.OuterHighlight = clBtnHighlight
      GutterBevel.OuterStyle = bsLowered
      GutterBevel.OuterOutline = osNone
      GutterColor = clGray
      TickColor = clMedGray
      TabOrder = 5
    end
    object GroupBox1: TGroupBox
      Left = 104
      Top = 108
      Width = 217
      Height = 41
      TabOrder = 6
      object RadioButton1: TRadioButton
        Left = 8
        Top = 16
        Width = 49
        Height = 17
        Caption = 'Low'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object RadioButton2: TRadioButton
        Left = 72
        Top = 16
        Width = 65
        Height = 17
        Caption = 'Normal'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object RadioButton3: TRadioButton
        Left = 152
        Top = 16
        Width = 49
        Height = 17
        Caption = 'High'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
    end
    object GroupBox2: TGroupBox
      Left = 96
      Top = 212
      Width = 233
      Height = 41
      TabOrder = 7
      object RadioButton4: TRadioButton
        Left = 8
        Top = 16
        Width = 49
        Height = 17
        Caption = 'Off'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object RadioButton5: TRadioButton
        Left = 72
        Top = 16
        Width = 65
        Height = 17
        Caption = 'Normal'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object RadioButton6: TRadioButton
        Left = 152
        Top = 16
        Width = 73
        Height = 17
        Caption = 'Afterglow'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
    end
    object VrTrackBar3: TVrTrackBar
      Left = 88
      Top = 272
      Width = 129
      Height = 17
      MaxValue = 20
      Position = 6
      GutterBevel.InnerShadow = clBtnShadow
      GutterBevel.InnerHighlight = clBtnHighlight
      GutterBevel.InnerWidth = 1
      GutterBevel.InnerStyle = bsNone
      GutterBevel.InnerSpace = 0
      GutterBevel.InnerColor = clBtnFace
      GutterBevel.OuterShadow = clBtnShadow
      GutterBevel.OuterHighlight = clBtnHighlight
      GutterBevel.OuterStyle = bsLowered
      GutterBevel.OuterOutline = osNone
      GutterColor = clGray
      TickColor = clMedGray
      TabOrder = 8
    end
    object GroupBox3: TGroupBox
      Left = 96
      Top = 300
      Width = 217
      Height = 41
      TabOrder = 9
      object RadioButton7: TRadioButton
        Left = 8
        Top = 16
        Width = 49
        Height = 17
        Caption = 'Low'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object RadioButton8: TRadioButton
        Left = 72
        Top = 16
        Width = 65
        Height = 17
        Caption = 'Normal'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
      object RadioButton9: TRadioButton
        Left = 152
        Top = 16
        Width = 49
        Height = 17
        Caption = 'High'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
      end
    end
    object GroupBox4: TGroupBox
      Left = 112
      Top = 420
      Width = 169
      Height = 41
      TabOrder = 10
      object RadioButton10: TRadioButton
        Left = 8
        Top = 16
        Width = 65
        Height = 17
        Caption = 'Cable 1'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object RadioButton11: TRadioButton
        Left = 96
        Top = 16
        Width = 65
        Height = 17
        Caption = 'Cable 2'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
    end
    object ComboBox1: TComboBox
      Left = 54
      Top = 33
      Width = 131
      Height = 21
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ItemHeight = 13
      ParentFont = False
      TabOrder = 11
      Text = 'Video_1'
    end
    object ComboBox2: TComboBox
      Left = 54
      Top = 81
      Width = 131
      Height = 21
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ItemHeight = 13
      ParentFont = False
      TabOrder = 12
      Text = 'Video_2'
    end
    object ComboBox3: TComboBox
      Left = 190
      Top = 169
      Width = 131
      Height = 21
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ItemHeight = 13
      ParentFont = False
      TabOrder = 13
      Text = 'Video_3'
    end
    object VrPowerButton1: TVrPowerButton
      Left = 19
      Top = 31
      Width = 25
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 14
    end
    object VrPowerButton2: TVrPowerButton
      Left = 19
      Top = 79
      Width = 25
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 15
    end
    object VrPowerButton3: TVrPowerButton
      Left = 157
      Top = 167
      Width = 25
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 16
    end
    object VrPowerButton4: TVrPowerButton
      Left = 17
      Top = 395
      Width = 86
      Height = 25
      Palette.Low = clGray
      Palette.High = clLime
      Caption = 'Freeze'
      Color = clMedGray
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 17
    end
  end
end
